/**
 * Serve the data plane to jsdom the way a CDN serves it to a browser.
 *
 * Works are no longer modules, so a test can no longer reach one with
 * `import()`. It reaches one the way a reader does: fetch the URL, verify
 * the hash. That is a truer test than the import ever was — the import
 * proved a bundler could find a file, and this proves the bytes on disk
 * satisfy the address the manifest published for them.
 *
 * `public/content/` is generated by `scripts/build-content-plane.mjs`,
 * which the test and build scripts run first.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const PUBLIC_ROOT = resolve(process.cwd(), 'public');

/**
 * Answer same-origin `/content/...` requests from `public/`, and hand
 * everything else to the fetch that was already installed.
 */
export function installContentPlaneFetch() {
    const upstream = globalThis.fetch?.bind(globalThis);

    globalThis.fetch = async function contentPlaneFetch(input, init) {
        const url = typeof input === 'string' ? input : input?.url ?? String(input);
        if (!url.startsWith('/content/')) {
            if (!upstream) throw new Error(`No fetch available for ${url}`);
            return upstream(input, init);
        }
        const path = join(PUBLIC_ROOT, url.replace(/^\//, '').split('?')[0]);
        if (!existsSync(path)) {
            return new Response('not found', { status: 404 });
        }
        return new Response(readFileSync(path, 'utf8'), {
            status: 200,
            headers: { 'content-type': 'application/json' }
        });
    };
}
