/**
 * Ingested Archive works.
 *
 * Each module under works/ is GENERATED by scripts/archive-ingest.mjs
 * and carries its own edition, source digest, and rights basis. This
 * file is the seam between those payloads and the Library registry:
 * it converts a work's sections into the reading-sequence shape the
 * rest of the system expects, and nothing more.
 *
 * LAZY BY NECESSITY
 * ─────────────────
 * These are whole books. Six of them statically imported took the
 * content bundle from 627 kB to 1.63 MB (548 kB gzipped) — every
 * visitor downloading every book before reading a word, and growing
 * with each acquisition.
 *
 * So the METADATA is eager and the TEXT is not. A card can show its
 * title, edition, and rights without the prose behind it; the payload
 * arrives only when a reader opens the work. This is what makes the
 * shelf extensible: the hundredth ingest costs a browsing reader
 * nothing.
 *
 * The rights evidence travels WITH the work rather than being restated
 * here. A second copy would be a second thing to keep true, and the
 * failure this Archive has already suffered once is a provenance record
 * that drifted from the text it described.
 */

/**
 * Metadata for every ingested work, and a loader for its text.
 *
 * The `meta` objects are small — a few hundred bytes each — and are
 * inlined here rather than imported, because importing them would pull
 * their module and with it the payload we are trying to defer. They are
 * copied from each generated module's *_META export; the test asserts
 * they still agree, so a re-ingest that changes an edition cannot leave
 * this file quietly stale.
 */
import { LITERATURE_WORKS } from './literature-catalog.js';
import { LEGACY_REINGESTED_WORKS } from './legacy-catalog.js';
import { divideSections } from './divisions.js';
import { loadArchiveSections } from '../../core/content-store.js';
// Precomputed by scripts/build-division-index.mjs. Divisions derive
// deterministically from bytes already committed, so they are derived
// once at build time rather than in every reader's browser — which is
// what lets a card say "365 chapters" without downloading Tolstoy.
//
// SERVED WORKS ONLY. The withheld corpus's divisions are a separate file that
// nothing shipping imports; `WORKS` below is already the served set, so this
// registry never asks for an entry that is not here.
import { STRUCTURED_IDS, withheldWorks } from './canon.js';
import {
    isArchiveEditionCertified,
    withArchiveReleaseIdentity
} from './certification.js';
import DIVISION_INDEX from './division-index.json' with { type: 'json' };

// Exported for the reachability guard, which must weigh every catalogue
// entry — including the ones this file writes itself.
export const CORE_WORKS = [
    {
        // THE FIRST WORK ACQUIRED FROM A STRUCTURED EDITION. Its poems, stanzas
        // and verse lines are read from the source's own markup rather than
        // inferred, and the ingest refuses a payload whose word count differs
        // from the source's (ARCHIVE-CANON-SPEC §3, ARCHIVE-CLEANSING-SPEC §2j).
        meta: {
            id: 'spoon-river-anthology',
            title: 'Spoon River Anthology',
            author: 'Edgar Lee Masters',
            shelf: 'received',
            edition: { publisher: 'Standard Ebooks', year: 1916, statement: 'the expanded 1916 edition' },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'oedipus-rex',
            title: 'Oedipus Rex',
            author: 'Sophocles',
            shelf: 'received',
            edition: { translator: 'Francis Storr', publisher: 'Standard Ebooks', year: 1912 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'confucius-analects',
            title: 'Analects',
            author: 'Confucius',
            shelf: 'received',
            edition: { translator: 'James Legge', publisher: 'Standard Ebooks', year: 1861 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'lyrical-ballads',
            title: 'Lyrical Ballads',
            author: 'William Wordsworth and Samuel Taylor Coleridge',
            shelf: 'received',
            edition: { publisher: 'Standard Ebooks', year: 1798 },
            basis: 'pre-1930-us'
        },
    },
    {
        // Re-sourced 2026-08-18 from a structured edition. The Gutenberg
        // payload was missing 303 words its heading detector had eaten, and
        // carried Civil Disobedience under Walden's title
        // (ARCHIVE-CLEANSING-SPEC §2j).
        meta: {
            id: 'literary-walden',
            title: 'Walden',
            author: 'Henry David Thoreau',
            shelf: 'received',
            edition: { publisher: 'Standard Ebooks', year: 1854, statement: 'Ticknor and Fields, 1854' },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'vitruvius-architecture',
            title: 'The Ten Books on Architecture',
            author: 'Vitruvius',
            shelf: 'received',
            edition: { translator: 'Morris Hicky Morgan', publisher: 'Harvard University Press', year: 1914 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'dow-composition',
            title: 'Composition',
            author: 'Arthur Wesley Dow',
            shelf: 'received',
            edition: { publisher: 'Doubleday, Page & Co.', year: 1913 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'ross-pure-design',
            title: 'A Theory of Pure Design',
            author: 'Denman Waldo Ross',
            shelf: 'received',
            edition: { publisher: 'Houghton, Mifflin & Co.', year: 1907 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'crane-line-and-form',
            title: 'Line and Form',
            author: 'Walter Crane',
            shelf: 'received',
            edition: { publisher: 'George Bell & Sons', year: 1900 },
            basis: 'author-death-70'
        },
    },
    {
        meta: {
            id: 'kandinsky-spiritual-in-art',
            title: 'Concerning the Spiritual in Art',
            author: 'Wassily Kandinsky',
            shelf: 'received',
            edition: { translator: 'Michael T. H. Sadler', publisher: 'Constable & Co.', year: 1914 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'dresser-decorative-design',
            title: 'Principles of Decorative Design',
            author: 'Christopher Dresser',
            shelf: 'received',
            edition: { publisher: 'Cassell, Petter & Galpin', year: 1873 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'epictetus-encheiridion',
            title: 'The Discourses and Encheiridion',
            author: 'Epictetus',
            shelf: 'received',
            edition: { translator: 'George Long', publisher: 'George Bell & Sons', year: 1890 },
            basis: 'author-death-70'
        },
    },
    {
        meta: {
            id: 'montaigne-essays',
            title: 'Essays',
            author: 'Michel de Montaigne',
            shelf: 'received',
            edition: { translator: 'Charles Cotton', publisher: 'ed. William Carew Hazlitt', year: 1877 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'okakura-book-of-tea',
            title: 'The Book of Tea',
            author: 'Kakuzo Okakura',
            shelf: 'received',
            edition: { publisher: 'Fox, Duffield & Co.', year: 1906 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'boethius-consolation',
            title: 'The Consolation of Philosophy',
            author: 'Boethius',
            shelf: 'received',
            edition: { translator: 'H. R. James', publisher: 'Elliot Stock', year: 1897 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'julian-revelations',
            title: 'Revelations of Divine Love',
            author: 'Julian of Norwich',
            shelf: 'received',
            edition: { publisher: 'ed. Grace Warrack, Methuen & Co.', year: 1901 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'kabir-songs',
            title: 'Songs of Kabir',
            author: 'Kabir',
            shelf: 'received',
            edition: { translator: 'Rabindranath Tagore', publisher: 'Macmillan', year: 1915 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'parker-australian-tales',
            title: 'Australian Legendary Tales',
            author: 'collected by K. Langloh Parker',
            shelf: 'received',
            edition: { publisher: 'David Nutt', year: 1896 },
            basis: 'author-death-70'
        },
    },
    {
        meta: {
            id: 'rasmussen-eskimo-tales',
            title: 'Eskimo Folk-Tales',
            author: 'collected by Knud Rasmussen',
            shelf: 'received',
            edition: { translator: 'W. J. Alexander Worster', publisher: 'Gyldendal', year: 1921 },
            basis: 'pre-1930-us'
        },
    },
    {
        meta: {
            id: 'mooney-cherokee-myths',
            title: 'Myths of the Cherokee',
            author: 'collected by James Mooney',
            shelf: 'received',
            edition: { publisher: 'Bureau of American Ethnology, Nineteenth Annual Report', year: 1900 },
            basis: 'us-government-work'
        },
    },
    {
        meta: {
            id: 'beckwith-anansi-stories',
            title: 'Jamaica Anansi Stories',
            author: 'collected by Martha Warren Beckwith',
            shelf: 'received',
            edition: { publisher: 'American Folk-Lore Society', year: 1924 },
            basis: 'pre-1930-us'
        },
    }
];

/**
 * WITHHELD FROM THE SHELF — a wrong edition, not a broken file.
 *
 * `npm run audit:text` scored these three far above everything else in
 * the Archive:
 *
 *     king-lear     39.0% of lines are critical apparatus
 *     hamlet        32.3%
 *     the-tempest   11.1%
 *     next highest   2.9   (and that one is clean)
 *
 * All three are the Cambridge Shakespeare of Clark and Wright, 1863-66
 * — and the catalog says so, in the edition statement, exactly as
 * recorded. Nothing was mislabelled. That edition simply prints a full
 * apparatus beneath every page, and the scan folded it into the play:
 *
 *     140. at] Ff. om. Qq.
 *     63. smote] smot Q2Q3FIF2F3.
 *
 * A reader who opens Hamlet gets pages of sigla and a dramatis personae
 * reading POLOXIUS before a line of verse. Hamlet and King Lear even
 * share a sourceSha256 — both were cut from one volume file.
 *
 * Withheld rather than deleted, and withheld rather than left up. The
 * Archive's own law is that a work which will not resolve is ABSENT,
 * never a broken frame; a text that is 39% apparatus does not resolve
 * as the work it claims to be. The payloads stay on disk so a
 * re-ingest can be compared against them.
 *
 * The list is by ID and carries its reason, so restoring one is
 * deleting a line — and so that nobody later wonders why Shakespeare is
 * missing from a library that holds Marlowe and Webster.
 */
const BUILT = [...CORE_WORKS, ...LEGACY_REINGESTED_WORKS, ...LITERATURE_WORKS];
const workId = work => work.meta?.id ?? work.id ?? '';

/**
 * THE SHELF IS THE CANON. Everything else is withheld with its reason, which
 * is the rule the three Shakespeares already obeyed — now applied to the whole
 * archive rather than to the works we happened to catch (ARCHIVE-CANON-SPEC).
 */
const WITHHELD = withheldWorks(BUILT.map(workId));

/** Every work the Archive is prepared to serve. */
export const WITHHELD_WORKS = WITHHELD;

const WORKS = BUILT.filter(work => !Object.hasOwn(WITHHELD, workId(work)))
    .map(work => Object.freeze({
        ...work,
        meta: withArchiveReleaseIdentity(work.meta)
    }));

/**
 * Candidate editions are visible only in an explicit review environment.
 * Public builds fail closed until a certification record matches their exact
 * source revision.  Development and the browser suite remain review tools.
 */
export function archiveReviewEnabled(env = import.meta.env) {
    return env?.DEV === true || env?.VITE_RISE_ARCHIVE_REVIEW === '1';
}

/**
 * DOES A PUBLIC BUILD SERVE WORK THAT IS NOT YET CERTIFIED?
 *
 * Yes, as a standing decision (Mateo, 2026-08-21), and it is written here
 * rather than set as a build variable so that it is legible in the source and
 * reversible in one line.
 *
 * Failing closed was the right default and the wrong outcome: no work has ever
 * been certified, so the public shelf served NOTHING while development served
 * all fifteen. The gate stays exactly as built — `isArchiveEditionCertified`
 * still answers per work against its exact source revision, and the shelf says
 * which state a reader is in — but a reader meets prepared work rather than an
 * empty room while the comparisons are done.
 *
 * Set this to `false` the day the certifications land, and the gate closes
 * behind them with nothing else to change.
 */
export const RELEASE_SERVES_UNCERTIFIED = true;

function serveCandidates() {
    return RELEASE_SERVES_UNCERTIFIED || archiveReviewEnabled();
}

export function releaseArchiveMetadata({ includeCandidates = serveCandidates() } = {}) {
    const works = includeCandidates
        ? WORKS
        : WORKS.filter(work => isArchiveEditionCertified(work.meta));
    return Object.freeze(works.map(work => work.meta));
}

/**
 * A long work is not one reading, and its own sections are not its
 * divisions.
 *
 * The generated `sections` are where the ingest's heading detector
 * fired, which is not the same thing as where the book divides: 27% of
 * their names are prose caught mid-sentence, and the true heading is
 * stripped out of the content entirely. Handing those to a reader
 * offers War and Peace in 445 pieces, a third of them titled with
 * fragments of Tolstoy's sentences.
 *
 * So divisions.js reads the sections as EVIDENCE and reconstructs the
 * work's real scheme — merging the mis-cut fragments back into the
 * chapter they were taken from, and refusing to divide at all when no
 * scheme survives verification.
 */
function sequencesFor(meta, sections) {
    // `declared`, exactly as getDivisions asks it. Without it this asked the
    // divider to re-derive a scheme the edition had already stated, which is
    // the flatten-and-reconstruct the structured ingest exists to end — one
    // module reading the declaration and its neighbour guessing.
    const { entries } = divideSections(sections,
        { declared: STRUCTURED_IDS.has(meta.id) });
    return entries.map((entry, i) => ({
        id: `${meta.id}-${i + 1}`,
        name: entry.label,
        title: entry.title,
        content: entry.content,
        words: entry.words,
        // Ingested prose carries no authored phrase marks. Left at the
        // work's own pace rather than the system default, because these
        // are arguments to be followed, not aphorisms to be dwelt on.
        wpm: 200,
        curve: 'flat',
        description: entry.title
            ? `${entry.label} — ${entry.title}`
            : `${entry.label} of ${meta.title}`
    }));
}

/** Library-registry records for every ingested work. */
/**
 * The registry, built once.
 *
 * Each record closes over its own `cached` payload and `divisions`, so
 * a work is imported and divided the first time it is opened and not
 * again. That was true per RECORD and false per CALL: this function
 * rebuilt every closure on every invocation, so the caches were always
 * empty and each caller re-imported and re-divided whole books.
 *
 * Invisible in the Library, which asks once. Fatal for a Journey, which
 * asks while showing its introduction and again when a reader presses
 * Begin — the second pass re-read Milton, Homer and Jünger from
 * nothing, and Begin sat on "Preparing…".
 */
const registries = new Map();

function registryFor(works, key) {
    if (registries.has(key)) return registries.get(key);
    const registry = works.map(({ meta }) => {
        const load = () => loadArchiveSections(meta.id);
        let cached = null;
        let divisions = null;
        return {
            id: meta.id,
            workId: meta.workId,
            editionId: meta.editionId,
            sourceRevision: meta.sourceRevision,
            certificationStatus: meta.certificationStatus,
            title: meta.title,
            author: meta.author,
            category: meta.shelf,
            // An edition names itself one of two ways, and they must not
            // be concatenated. Interpolating both fields blindly gave
            // "Homer · undefined, 1883" where a publisher was absent,
            // and then "…Ernest Myers, 1883, 1883" once the hole was
            // patched, because a `statement` already carries its year.
            tradition: meta.edition.publisher
                ? `${meta.edition.publisher}, ${meta.edition.year}`
                : (meta.edition.statement || String(meta.edition.year || '')),
            description: meta.edition.translator
                ? `${meta.title}, translated by ${meta.edition.translator}.`
                : `${meta.title}.`,
            // What the work holds, and what IT calls them. Every card
            // used to read "0 verses" — a count that was wrong in a
            // noun that was wrong — because the payload had not loaded
            // and nothing else knew.
            chapterCount: DIVISION_INDEX[meta.id]?.count ?? null,
            chapterNoun: DIVISION_INDEX[meta.id]?.noun ?? null,
            chapterTitled: DIVISION_INDEX[meta.id]?.titled === true,
            wordCount: DIVISION_INDEX[meta.id]?.words ?? null,
            // A long work is entered at a division, not at its first
            // word. The Library reads this to decide whether to offer
            // a table of contents; it stays null until the payload
            // arrives, because the divisions are derived from it.
            divisions: null,
            getDivisions: async () => {
                if (!divisions) {
                    divisions = divideSections(await load(),
                        { declared: STRUCTURED_IDS.has(meta.id) });
                }
                return divisions;
            },
            /**
             * WHAT WE HOLD, as opposed to what we show.
             *
             * `getDivisions` is a display selection: it drops a
             * contents page, folds mis-cut fragments, and refuses a
             * scheme it cannot verify. Every one of those is the right
             * call for a reader and the wrong basis for an integrity
             * check — the question "are these the right bytes?" is
             * about the payload, and it must not be answerable
             * differently because the shelf changed how it presents
             * them.
             *
             * The identity invariant read the divisions and began
             * failing for four works the moment the index stopped being
             * offered as chapter one, which was a true statement about
             * the display and a false one about the holding.
             */
            getSections: async () => load(),
            defaultCurve: 'flat',
            defaultWpm: 200,
            tags: ['archive', 'ingested', meta.shelf],
            provider: 'archive-ingest',
            // The text arrives when asked for, once.
            getSequences: async () => {
                if (!cached) cached = sequencesFor(meta, await load());
                return cached;
            },
            provenance: {
                translator: meta.edition.translator,
                year: meta.edition.year,
                basis: meta.basis,
                workId: meta.workId,
                editionId: meta.editionId,
                sourceRevision: meta.sourceRevision,
                certificationStatus: meta.certificationStatus
            }
        };
    });
    registries.set(key, registry);
    return registry;
}

/** All admitted candidates, for audits and explicit review tooling. */
export function ingestedArchiveTexts() {
    return registryFor(WORKS, 'review');
}

/** Editions a reader-facing surface may expose in this build. */
/** How many served works have no certification record for their exact bytes. */
export function uncertifiedCount() {
    return releaseArchiveMetadata().filter(meta => !isArchiveEditionCertified(meta)).length;
}

export function releaseArchiveTexts({ includeCandidates = serveCandidates() } = {}) {
    const works = includeCandidates
        ? WORKS
        : WORKS.filter(work => isArchiveEditionCertified(work.meta));
    return registryFor(works, includeCandidates ? 'review' : 'release');
}

/** The declared metadata, for tests that check it against the payloads. */
export const INGESTED_META = WORKS.map(w => w.meta);
