/**
 * Ingested Archive works.
 *
 * Each module under works/ is GENERATED by scripts/archive-ingest.mjs
 * and carries its own edition, source digest, and rights basis. This
 * file is the seam between those payloads and the Library registry:
 * it converts a work's sections into the reading-sequence shape the
 * rest of the system expects, and nothing more.
 *
 * LAZY BY NECESSITY
 * ─────────────────
 * These are whole books. Six of them statically imported took the
 * content bundle from 627 kB to 1.63 MB (548 kB gzipped) — every
 * visitor downloading every book before reading a word, and growing
 * with each acquisition.
 *
 * So the METADATA is eager and the TEXT is not. A card can show its
 * title, edition, and rights without the prose behind it; the payload
 * arrives only when a reader opens the work. This is what makes the
 * shelf extensible: the hundredth ingest costs a browsing reader
 * nothing.
 *
 * The rights evidence travels WITH the work rather than being restated
 * here. A second copy would be a second thing to keep true, and the
 * failure this Archive has already suffered once is a provenance record
 * that drifted from the text it described.
 */

/**
 * Metadata for every ingested work, and a loader for its text.
 *
 * The `meta` objects are small — a few hundred bytes each — and are
 * inlined here rather than imported, because importing them would pull
 * their module and with it the payload we are trying to defer. They are
 * copied from each generated module's *_META export; the test asserts
 * they still agree, so a re-ingest that changes an edition cannot leave
 * this file quietly stale.
 */
import { LITERATURE_WORKS } from './literature-catalog.js';
import { LEGACY_REINGESTED_WORKS } from './legacy-catalog.js';
import { divideSections } from './divisions.js';
// Precomputed by scripts/build-division-index.mjs. Divisions derive
// deterministically from bytes already committed, so they are derived
// once at build time rather than in every reader's browser — which is
// what lets a card say "365 chapters" without downloading Tolstoy.
import DIVISION_INDEX from './division-index.json';

const CORE_WORKS = [
    {
        meta: {
            id: 'vitruvius-architecture',
            title: 'The Ten Books on Architecture',
            author: 'Vitruvius',
            shelf: 'form',
            edition: { translator: 'Morris Hicky Morgan', publisher: 'Harvard University Press', year: 1914 },
            basis: 'pre-1930-us'
        },
        load: () => import('./works/vitruvius-architecture.js')
            .then(m => m.VITRUVIUS_ARCHITECTURE_SECTIONS)
    },
    {
        meta: {
            id: 'dow-composition',
            title: 'Composition',
            author: 'Arthur Wesley Dow',
            shelf: 'form',
            edition: { publisher: 'Doubleday, Page & Co.', year: 1913 },
            basis: 'pre-1930-us'
        },
        load: () => import('./works/dow-composition.js')
            .then(m => m.DOW_COMPOSITION_SECTIONS)
    },
    {
        meta: {
            id: 'ross-pure-design',
            title: 'A Theory of Pure Design',
            author: 'Denman Waldo Ross',
            shelf: 'form',
            edition: { publisher: 'Houghton, Mifflin & Co.', year: 1907 },
            basis: 'pre-1930-us'
        },
        load: () => import('./works/ross-pure-design.js')
            .then(m => m.ROSS_PURE_DESIGN_SECTIONS)
    },
    {
        meta: {
            id: 'crane-line-and-form',
            title: 'Line and Form',
            author: 'Walter Crane',
            shelf: 'form',
            edition: { publisher: 'George Bell & Sons', year: 1900 },
            basis: 'author-death-70'
        },
        load: () => import('./works/crane-line-and-form.js')
            .then(m => m.CRANE_LINE_AND_FORM_SECTIONS)
    },
    {
        meta: {
            id: 'kandinsky-spiritual-in-art',
            title: 'Concerning the Spiritual in Art',
            author: 'Wassily Kandinsky',
            shelf: 'form',
            edition: { translator: 'Michael T. H. Sadler', publisher: 'Constable & Co.', year: 1914 },
            basis: 'pre-1930-us'
        },
        load: () => import('./works/kandinsky-spiritual-in-art.js')
            .then(m => m.KANDINSKY_SPIRITUAL_IN_ART_SECTIONS)
    },
    {
        meta: {
            id: 'dresser-decorative-design',
            title: 'Principles of Decorative Design',
            author: 'Christopher Dresser',
            shelf: 'form',
            edition: { publisher: 'Cassell, Petter & Galpin', year: 1873 },
            basis: 'pre-1930-us'
        },
        load: () => import('./works/dresser-decorative-design.js')
            .then(m => m.DRESSER_DECORATIVE_DESIGN_SECTIONS)
    },
    {
        meta: {
            id: 'epictetus-encheiridion',
            title: 'The Discourses and Encheiridion',
            author: 'Epictetus',
            shelf: 'western',
            edition: { translator: 'George Long', publisher: 'George Bell & Sons', year: 1890 },
            basis: 'author-death-70'
        },
        load: () => import('./works/epictetus-encheiridion.js')
            .then(m => m.EPICTETUS_ENCHEIRIDION_SECTIONS)
    },
    {
        meta: {
            id: 'montaigne-essays',
            title: 'Essays',
            author: 'Michel de Montaigne',
            shelf: 'western',
            edition: { translator: 'Charles Cotton', publisher: 'ed. William Carew Hazlitt', year: 1877 },
            basis: 'pre-1930-us'
        },
        load: () => import('./works/montaigne-essays.js')
            .then(m => m.MONTAIGNE_ESSAYS_SECTIONS)
    },
    {
        meta: {
            id: 'okakura-book-of-tea',
            title: 'The Book of Tea',
            author: 'Kakuzo Okakura',
            shelf: 'eastern',
            edition: { publisher: 'Fox, Duffield & Co.', year: 1906 },
            basis: 'pre-1930-us'
        },
        load: () => import('./works/okakura-book-of-tea.js')
            .then(m => m.OKAKURA_BOOK_OF_TEA_SECTIONS)
    },
    {
        meta: {
            id: 'boethius-consolation',
            title: 'The Consolation of Philosophy',
            author: 'Boethius',
            shelf: 'western',
            edition: { translator: 'H. R. James', publisher: 'Elliot Stock', year: 1897 },
            basis: 'pre-1930-us'
        },
        load: () => import('./works/boethius-consolation.js')
            .then(m => m.BOETHIUS_CONSOLATION_SECTIONS)
    },
    {
        meta: {
            id: 'julian-revelations',
            title: 'Revelations of Divine Love',
            author: 'Julian of Norwich',
            shelf: 'western',
            edition: { publisher: 'ed. Grace Warrack, Methuen & Co.', year: 1901 },
            basis: 'pre-1930-us'
        },
        load: () => import('./works/julian-revelations.js')
            .then(m => m.JULIAN_REVELATIONS_SECTIONS)
    },
    {
        meta: {
            id: 'kabir-songs',
            title: 'Songs of Kabir',
            author: 'Kabir',
            shelf: 'eastern',
            edition: { translator: 'Rabindranath Tagore', publisher: 'Macmillan', year: 1915 },
            basis: 'pre-1930-us'
        },
        load: () => import('./works/kabir-songs.js')
            .then(m => m.KABIR_SONGS_SECTIONS)
    },
    {
        meta: {
            id: 'parker-australian-tales',
            title: 'Australian Legendary Tales',
            author: 'collected by K. Langloh Parker',
            shelf: 'indigenous',
            edition: { publisher: 'David Nutt', year: 1896 },
            basis: 'author-death-70'
        },
        load: () => import('./works/parker-australian-tales.js')
            .then(m => m.PARKER_AUSTRALIAN_TALES_SECTIONS)
    },
    {
        meta: {
            id: 'rasmussen-eskimo-tales',
            title: 'Eskimo Folk-Tales',
            author: 'collected by Knud Rasmussen',
            shelf: 'indigenous',
            edition: { translator: 'W. J. Alexander Worster', publisher: 'Gyldendal', year: 1921 },
            basis: 'pre-1930-us'
        },
        load: () => import('./works/rasmussen-eskimo-tales.js')
            .then(m => m.RASMUSSEN_ESKIMO_TALES_SECTIONS)
    },
    {
        meta: {
            id: 'mooney-cherokee-myths',
            title: 'Myths of the Cherokee',
            author: 'collected by James Mooney',
            shelf: 'indigenous',
            edition: { publisher: 'Bureau of American Ethnology, Nineteenth Annual Report', year: 1900 },
            basis: 'us-government-work'
        },
        load: () => import('./works/mooney-cherokee-myths.js')
            .then(m => m.MOONEY_CHEROKEE_MYTHS_SECTIONS)
    },
    {
        meta: {
            id: 'beckwith-anansi-stories',
            title: 'Jamaica Anansi Stories',
            author: 'collected by Martha Warren Beckwith',
            shelf: 'indigenous',
            edition: { publisher: 'American Folk-Lore Society', year: 1924 },
            basis: 'pre-1930-us'
        },
        load: () => import('./works/beckwith-anansi-stories.js')
            .then(m => m.BECKWITH_ANANSI_STORIES_SECTIONS)
    }
];

const WORKS = [...CORE_WORKS, ...LEGACY_REINGESTED_WORKS, ...LITERATURE_WORKS];

/**
 * A long work is not one reading, and its own sections are not its
 * divisions.
 *
 * The generated `sections` are where the ingest's heading detector
 * fired, which is not the same thing as where the book divides: 27% of
 * their names are prose caught mid-sentence, and the true heading is
 * stripped out of the content entirely. Handing those to a reader
 * offers War and Peace in 445 pieces, a third of them titled with
 * fragments of Tolstoy's sentences.
 *
 * So divisions.js reads the sections as EVIDENCE and reconstructs the
 * work's real scheme — merging the mis-cut fragments back into the
 * chapter they were taken from, and refusing to divide at all when no
 * scheme survives verification.
 */
function sequencesFor(meta, sections) {
    const { entries } = divideSections(sections);
    return entries.map((entry, i) => ({
        id: `${meta.id}-${i + 1}`,
        name: entry.label,
        title: entry.title,
        content: entry.content,
        words: entry.words,
        // Ingested prose carries no authored phrase marks. Left at the
        // work's own pace rather than the system default, because these
        // are arguments to be followed, not aphorisms to be dwelt on.
        wpm: 200,
        curve: 'flat',
        description: entry.title
            ? `${entry.label} — ${entry.title}`
            : `${entry.label} of ${meta.title}`
    }));
}

/** Library-registry records for every ingested work. */
/**
 * The registry, built once.
 *
 * Each record closes over its own `cached` payload and `divisions`, so
 * a work is imported and divided the first time it is opened and not
 * again. That was true per RECORD and false per CALL: this function
 * rebuilt every closure on every invocation, so the caches were always
 * empty and each caller re-imported and re-divided whole books.
 *
 * Invisible in the Library, which asks once. Fatal for a Journey, which
 * asks while showing its introduction and again when a reader presses
 * Begin — the second pass re-read Milton, Homer and Jünger from
 * nothing, and Begin sat on "Preparing…".
 */
let registry = null;

export function ingestedArchiveTexts() {
    if (registry) return registry;
    registry = WORKS.map(({ meta, load }) => {
        let cached = null;
        let divisions = null;
        return {
            id: meta.id,
            title: meta.title,
            author: meta.author,
            category: meta.shelf,
            // An edition names itself one of two ways, and they must not
            // be concatenated. Interpolating both fields blindly gave
            // "Homer · undefined, 1883" where a publisher was absent,
            // and then "…Ernest Myers, 1883, 1883" once the hole was
            // patched, because a `statement` already carries its year.
            tradition: meta.edition.publisher
                ? `${meta.edition.publisher}, ${meta.edition.year}`
                : (meta.edition.statement || String(meta.edition.year || '')),
            description: meta.edition.translator
                ? `${meta.title}, translated by ${meta.edition.translator}.`
                : `${meta.title}.`,
            // What the work holds, and what IT calls them. Every card
            // used to read "0 verses" — a count that was wrong in a
            // noun that was wrong — because the payload had not loaded
            // and nothing else knew.
            chapterCount: DIVISION_INDEX[meta.id]?.count ?? null,
            chapterNoun: DIVISION_INDEX[meta.id]?.noun ?? null,
            chapterTitled: DIVISION_INDEX[meta.id]?.titled === true,
            wordCount: DIVISION_INDEX[meta.id]?.words ?? null,
            // A long work is entered at a division, not at its first
            // word. The Library reads this to decide whether to offer
            // a table of contents; it stays null until the payload
            // arrives, because the divisions are derived from it.
            divisions: null,
            getDivisions: async () => {
                if (!divisions) divisions = divideSections(await load());
                return divisions;
            },
            defaultCurve: 'flat',
            defaultWpm: 200,
            tags: ['archive', 'ingested', meta.shelf],
            provider: 'archive-ingest',
            // The text arrives when asked for, once.
            getSequences: async () => {
                if (!cached) cached = sequencesFor(meta, await load());
                return cached;
            },
            provenance: {
                translator: meta.edition.translator,
                year: meta.edition.year,
                basis: meta.basis
            }
        };
    });
    return registry;
}

/** The declared metadata, for tests that check it against the payloads. */
export const INGESTED_META = WORKS.map(w => w.meta);
