/** GENERATED by scripts/literature-ingest.mjs; do not hand-edit. */
export const LITERATURE_WORKS = [
    {
        meta: {"id":"the-iliad","title":"The Iliad","author":"Homer","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"translator":"William Cullen Bryant","publisher":"Standard Ebooks","year":1870},"basis":"pre-1930-us","payloadChecksum":"81f7fa6a67d7e0e1c71e60bc6a6ed5645e785643d18587f753d218b67011b828","chars":845813,"sections":24,"structuredSource":"https://raw.githubusercontent.com/standardebooks/homer_the-iliad_william-cullen-bryant"},
        load: () => import('./works/the-iliad.js')
            .then(module => module.THE_ILIAD_SECTIONS)
    },
    {
        meta: {"id":"the-odyssey","title":"The Odyssey","author":"Homer","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Samuel Butler, Longmans, Green, 1900","year":1900},"basis":"pre-1930-us","sourceSha256":"ca2ebb58066e0e40c42e1e149b7079f392f6790c2bf5babea262459961b3b90f","payloadChecksum":"efc9c2fc4f87d2e29b6d5cd4a4e3437e4b9774c04a2a6b6be67c893e1172ffad","chars":678750,"sections":25},
        load: () => import('./works/the-odyssey.js')
            .then(module => module.THE_ODYSSEY_SECTIONS)
    },
    {
        meta: {"id":"the-aeneid","title":"The Aeneid","author":"Virgil","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. John Dryden, 1697","year":1697},"basis":"author-death-70","sourceSha256":"a7f04d408682906c73d833b71ed2e89f1e2b752a33c2c36975d260c3427b1d87","payloadChecksum":"fa7e5a8e04fae65d813adefbf2e2bb00796e327493910e0306e45f14b6deabe6","chars":696742,"sections":12},
        load: () => import('./works/the-aeneid.js')
            .then(module => module.THE_AENEID_SECTIONS)
    },
    {
        meta: {"id":"metamorphoses","title":"Metamorphoses","author":"Ovid","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"translator":"various translators","publisher":"Standard Ebooks","year":1717},"basis":"pre-1930-us","payloadChecksum":"f5861013b1766d523a463b4adb073e04f554957e448f2977be1bafd187a445bb","chars":739091,"sections":147,"structuredSource":"https://raw.githubusercontent.com/standardebooks/ovid_metamorphoses_various-translators"},
        load: () => import('./works/metamorphoses.js')
            .then(module => module.METAMORPHOSES_SECTIONS)
    },
    {
        meta: {"id":"beowulf","title":"Beowulf","author":"anonymous","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Francis B. Gummere, 1910","year":1910},"basis":"pre-1930-us","sourceSha256":"dacf2aaac91ccece3112decd297ce8c9ff54bc6f6b140bcfe26abdf23a73e7a9","payloadChecksum":"0db7555d8c53c10e4f94713c862ccfb66b69c782208d5272a61ae055a8344068","chars":147246,"sections":1},
        load: () => import('./works/beowulf.js')
            .then(module => module.BEOWULF_SECTIONS)
    },
    {
        meta: {"id":"the-divine-comedy","title":"The Divine Comedy","author":"Dante Alighieri","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"classical","edition":{"translator":"Henry Wadsworth Longfellow","publisher":"Standard Ebooks","year":1867},"basis":"pre-1930-us","payloadChecksum":"51ea537a8680398db97b39863c00f7d093092bdaa7c63866a3eed3c47b4f698d","chars":620310,"sections":103,"structuredSource":"https://raw.githubusercontent.com/standardebooks/dante-alighieri_the-divine-comedy_henry-wadsworth-longfellow"},
        load: () => import('./works/the-divine-comedy.js')
            .then(module => module.THE_DIVINE_COMEDY_SECTIONS)
    },
    {
        meta: {"id":"the-nibelungenlied","title":"The Nibelungenlied","author":"anonymous","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Daniel B. Shumway, Houghton Mifflin, 1909","year":1909},"basis":"pre-1930-us","sourceSha256":"8c5d2e1244ef2a1b1f1a64f63ec98f99c500703e00f00480e8045f80ce7bb833","payloadChecksum":"e717ba2f7d6094658520216b1ce360cae30543a42abf3525d96d9461455196ca","chars":568093,"sections":41},
        load: () => import('./works/the-nibelungenlied.js')
            .then(module => module.THE_NIBELUNGENLIED_SECTIONS)
    },
    {
        meta: {"id":"the-song-of-roland","title":"The Song of Roland","author":"anonymous","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. C. K. Scott-Moncrieff, Chapman & Hall, 1919","year":1919},"basis":"pre-1930-us","sourceSha256":"b2c4ca23656b8dad4c6f03087b5b4eb2eb90b727f7a2533757ab7322eb3ffa60","payloadChecksum":"b72efb6170878396670363547989dd6dbe4c8dc3e0dba38378cd6f87cd5de8a4","chars":192205,"sections":1},
        load: () => import('./works/the-song-of-roland.js')
            .then(module => module.THE_SONG_OF_ROLAND_SECTIONS)
    },
    {
        meta: {"id":"the-kalevala","title":"The Kalevala","author":"traditional singers; compiled by Elias Lönnrot","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. John Martin Crawford, 2 vols., 1888","year":1888},"basis":"author-death-70","sourceSha256":"04215ac4c7c559f85cd350649edf2454e37814721fd6cc38deafc43ca4f52d94","payloadChecksum":"20394a0abb529b94db3171de4bf6f6778158a2361cac367485d096be623e4ce6","chars":816556,"sections":55},
        load: () => import('./works/the-kalevala.js')
            .then(module => module.THE_KALEVALA_SECTIONS)
    },
    {
        meta: {"id":"the-canterbury-tales-and-other-poems","title":"The Canterbury Tales and Other Poems","author":"Geoffrey Chaucer","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"classical","edition":{"statement":"ed. D. Laing Purves, 1870","year":1870},"basis":"author-death-70","sourceSha256":"1b9e54bb090b3c9d7dbcd6e6130707f6b43da41feaf080c6d607217bf15d4802","payloadChecksum":"31500f4e434826b4da46e4a4de6777fdc499f042a6248f1e5531b37dd234acaf","chars":1650757,"sections":1},
        load: () => import('./works/the-canterbury-tales-and-other-poems.js')
            .then(module => module.THE_CANTERBURY_TALES_AND_OTHER_POEMS_SECTIONS)
    },
    {
        meta: {"id":"le-morte-darthur","title":"Le Morte Darthur","author":"Sir Thomas Malory","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"Everyman's Library ed. Ernest Rhys, 1906","year":1906},"basis":"pre-1930-us","sourceSha256":"1e0eff52571d91782904eca13fbfcdcf32d1cb043c52e0610036fd6012eefd2d","payloadChecksum":"fdf7695fdfcbb9d1ee8dbc8b3936e67ffeda55f69b69f818ce4af96796d4b915","chars":1886842,"sections":511},
        load: () => import('./works/le-morte-darthur.js')
            .then(module => module.LE_MORTE_DARTHUR_SECTIONS)
    },
    {
        meta: {"id":"the-decameron","title":"The Decameron","author":"Giovanni Boccaccio","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"classical","edition":{"statement":"trans. John Payne, 1886","year":1886},"basis":"author-death-70","sourceSha256":"e9928094dcca57ddf06ab06b4026f59d1cff2ee3cde3e2fac53f6068b3af0c51","payloadChecksum":"409391553362aaf6a851a071fbc64b43f1fa03945ab9d2e3707189014f556075","chars":1701019,"sections":1},
        load: () => import('./works/the-decameron.js')
            .then(module => module.THE_DECAMERON_SECTIONS)
    },
    {
        meta: {"id":"the-house-of-atreus","title":"The House of Atreus","author":"Aeschylus","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"classical","edition":{"statement":"trans. E. D. A. Morshead, 1881","year":1881},"basis":"author-death-70","sourceSha256":"c8a94c9c00d51703fd000060f3d33dcc17b8b03dff98a0bf001d605345feb1a2","payloadChecksum":"f04776502d09a633421030cf2f747c13f11e5da20a12f129d71369f90263461b","chars":195300,"sections":1},
        load: () => import('./works/the-house-of-atreus.js')
            .then(module => module.THE_HOUSE_OF_ATREUS_SECTIONS)
    },
    {
        meta: {"id":"the-oedipus-trilogy","title":"The Oedipus Trilogy","author":"Sophocles","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Francis Storr, Loeb Classical Library, 1912","year":1912},"basis":"pre-1930-us","sourceSha256":"3a5c1d02a04e5743df141bf0ca3480ab3774a9713846522921814d7cd65d7562","payloadChecksum":"357b10c42d858ce258b57199eb2ca69e72114402d64504d1ee310cbe5b37d1a7","chars":214753,"sections":1},
        load: () => import('./works/the-oedipus-trilogy.js')
            .then(module => module.THE_OEDIPUS_TRILOGY_SECTIONS)
    },
    {
        meta: {"id":"the-bacchae","title":"The Bacchae","author":"Euripides","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Gilbert Murray, 2nd ed., George Allen, 1906","year":1906},"basis":"author-death-70","sourceSha256":"a7409c885b019b3e8111e6e59530d3c33f08cb57224a2ff9e6464175da8f1140","payloadChecksum":"2f091b4f43a240fb6c466dce009fea56b446d75dc48faff4375cbe3075ab1d22","chars":109682,"sections":1},
        load: () => import('./works/the-bacchae.js')
            .then(module => module.THE_BACCHAE_SECTIONS)
    },
    {
        meta: {"id":"hamlet","title":"Hamlet","author":"William Shakespeare","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Cambridge Shakespeare, ed. W. G. Clark and W. Aldis Wright, 1863–66","year":1863},"basis":"author-death-70","sourceSha256":"7b0dcbe9e291d018f1755e7b5384d188bd705192a1fe0cc62ce47333f68db0eb","payloadChecksum":"07c1d024d4516458aa3cf56da30f44557c4d962df688e3cdccec5f40d1a1eec4","chars":564718,"sections":77},
        load: () => import('./works/hamlet.js')
            .then(module => module.HAMLET_SECTIONS)
    },
    {
        meta: {"id":"king-lear","title":"King Lear","author":"William Shakespeare","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Cambridge Shakespeare, ed. Clark and Wright, 1863–66","year":1863},"basis":"author-death-70","sourceSha256":"7b0dcbe9e291d018f1755e7b5384d188bd705192a1fe0cc62ce47333f68db0eb","payloadChecksum":"712c073d2c982d9990f9ccc4ceac79470652e0316a084d77838d50f62c127172","chars":427076,"sections":87},
        load: () => import('./works/king-lear.js')
            .then(module => module.KING_LEAR_SECTIONS)
    },
    {
        meta: {"id":"the-tempest","title":"The Tempest","author":"William Shakespeare","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Cambridge Shakespeare, ed. Clark and Wright, 1863–66","year":1863},"basis":"author-death-70","sourceSha256":"6387ed27885f9ee6c0b920edf7e7ce2311728acc98a9331c84952ed63ceb1227","payloadChecksum":"fa5f4920f45fe7c8ab12aafe728de1d8e8757f975c90d74c2e242f4612e3e256","chars":156938,"sections":38},
        load: () => import('./works/the-tempest.js')
            .then(module => module.THE_TEMPEST_SECTIONS)
    },
    {
        meta: {"id":"the-tragical-history-of-doctor-faustus","title":"The Tragical History of Doctor Faustus","author":"Christopher Marlowe","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Alexander Dyce text of the 1604 A-text, 1870s","year":1604},"basis":"author-death-70","sourceSha256":"a60b48ff5483f8b62710b5d77b545c0ef2c97f077f519d277ee0279556362ebc","payloadChecksum":"d2f350482fc426e8fe8b8c7f5705db36ec408a2a14a4af5095b4a77c9d8715b2","chars":124323,"sections":1},
        load: () => import('./works/the-tragical-history-of-doctor-faustus.js')
            .then(module => module.THE_TRAGICAL_HISTORY_OF_DOCTOR_FAUSTUS_SECTIONS)
    },
    {
        meta: {"id":"the-duchess-of-malfi","title":"The Duchess of Malfi","author":"John Webster","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Harvard Classics-era public-domain text","year":null},"basis":"author-death-70","sourceSha256":"18e701cec034a9b0ebe7b4d8d1513963ecbea9f58a641750aef49319ed78a29c","payloadChecksum":"8169d194b4b69300bbcb9777033d45bf03e3444c6b0e7ed6ebef51179d5b1418","chars":168823,"sections":20},
        load: () => import('./works/the-duchess-of-malfi.js')
            .then(module => module.THE_DUCHESS_OF_MALFI_SECTIONS)
    },
    {
        meta: {"id":"phaedra","title":"Phaedra","author":"Jean Racine","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Robert Bruce Boswell, in *The French Classical Romances*, 1899","year":1899},"basis":"author-death-70","sourceSha256":"3a8b10eff0303cfb76c6133bbd434502ea3dfc3b7b39590b5f103fbacdfbed67","payloadChecksum":"0054ea03630a503749111742db698c7fffbc7b587c6a973e0c7f7457814f5b76","chars":97622,"sections":31},
        load: () => import('./works/phaedra.js')
            .then(module => module.PHAEDRA_SECTIONS)
    },
    {
        meta: {"id":"faust","title":"Faust","author":"Johann Wolfgang von Goethe","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Bayard Taylor, 2 vols., 1870–71; Boston/New York Houghton Mifflin reissue, 1912","year":1870},"basis":"pre-1930-us","sourceSha256":"d5b2eb2eab24558294f3717ad21e7d357adbe2bb66def99e86a17cabbce04d46","payloadChecksum":"48558ba46c674169deb409bfca5c84c31a80af8c963fd580f4eb8a8ee2062198","chars":870458,"sections":16},
        load: () => import('./works/faust.js')
            .then(module => module.FAUST_SECTIONS)
    },
    {
        meta: {"id":"a-doll-s-house","title":"A Doll's House","author":"Henrik Ibsen","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. William Archer, 1889","year":1889},"basis":"author-death-70","sourceSha256":"11003afc47b90b4668d9fefc2f7cfe81c5457f08aa6347041d1d8f629bdcaff0","payloadChecksum":"c931391659daa8a1fa8204dc818619d94bf3cad5915d7daee55dd8c1e2ead272","chars":142216,"sections":4},
        load: () => import('./works/a-doll-s-house.js')
            .then(module => module.A_DOLL_S_HOUSE_SECTIONS)
    },
    {
        meta: {"id":"don-quixote","title":"Don Quixote","author":"Miguel de Cervantes","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"trans. John Ormsby, 1885","year":1885},"basis":"author-death-70","sourceSha256":"b11a0b182413f1dea386343f10563b851dc905c6d649f636276afd237a2fdf8a","payloadChecksum":"8865f81caaf480674661b8a5dd941cde1755b846d8c222df9109cb23dc4feba5","chars":2298922,"sections":145},
        load: () => import('./works/don-quixote.js')
            .then(module => module.DON_QUIXOTE_SECTIONS)
    },
    {
        meta: {"id":"paradise-lost","title":"Paradise Lost","author":"John Milton","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"publisher":"Standard Ebooks","year":1667},"basis":"pre-1930-us","payloadChecksum":"2a8585cc47b64b610a2a4f8a693eadc7557849e35f80ebe65bc7ef64a4c5957f","chars":470767,"sections":12,"structuredSource":"https://raw.githubusercontent.com/standardebooks/john-milton_paradise-lost"},
        load: () => import('./works/paradise-lost.js')
            .then(module => module.PARADISE_LOST_SECTIONS)
    },
    {
        meta: {"id":"the-faerie-queene","title":"The Faerie Queene","author":"Edmund Spenser","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"ed. John W. Hales, Everyman's Library, 2 vols., J. M. Dent/E. P. Dutton, London/New York, 1909; Internet Archive [vol. I `faeriequeenedis01spen`](https://archive.org/details/faeriequeenedis01spen) and [vol. II `faeriequeenedis02spen`](https://archive.org/details/faeriequeenedis02spen); `pre-1930-us`","year":1909},"basis":"pre-1930-us","sourceSha256":"af7a180072f167953c4c45bdddd2e694a14c67da6770eb0cfb205f075cd77ea9","payloadChecksum":"c78804532adbb24bc6972f62cb4ada6337fafa3a52efaf03b4d77aa93bae7987","chars":2050137,"sections":159},
        load: () => import('./works/the-faerie-queene.js')
            .then(module => module.THE_FAERIE_QUEENE_SECTIONS)
    },
    {
        meta: {"id":"the-troubadours","title":"The Troubadours","author":"named Occitan poets; translated and discussed by H. J. Chaytor","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Cambridge University Press, 1912","year":1912},"basis":"pre-1930-us","sourceSha256":"04b1ed51f9d92fc2b4f993b465410fa0ce994a8b50042ac35d46d0db04ee4b91","payloadChecksum":"62a0d263d21bbdf24e9b60c7e42938795fd33a1fb93d926dfd19314ad2cf7b46","chars":199679,"sections":22},
        load: () => import('./works/the-troubadours.js')
            .then(module => module.THE_TROUBADOURS_SECTIONS)
    },
    {
        meta: {"id":"moby-dick-or-the-whale","title":"Moby-Dick; or, The Whale","author":"Herman Melville","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"Harper & Brothers, New York, 1851","year":1851},"basis":"author-death-70","sourceSha256":"22acc42134f30ad8612f55fcf17d83e802adfe169c99c0663c1f211a1dacfb80","payloadChecksum":"a1e8758285526ea61b490ff9800b9fec5810b275b5823c2ecbda6b0b083ed81c","chars":1218799,"sections":152},
        load: () => import('./works/moby-dick-or-the-whale.js')
            .then(module => module.MOBY_DICK_OR_THE_WHALE_SECTIONS)
    },
    {
        meta: {"id":"pride-and-prejudice","title":"Pride and Prejudice","author":"Jane Austen","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"1813 text","year":1813},"basis":"author-death-70","sourceSha256":"84da0929bbf56fbabf3be812964d2a0384e08915dcefa896f560d5ea8a71f5d8","payloadChecksum":"f023076387bedc196397fb82a63ae91532a68cf5eb1821a6d2ea6629b4fd8ccb","chars":728530,"sections":62},
        load: () => import('./works/pride-and-prejudice.js')
            .then(module => module.PRIDE_AND_PREJUDICE_SECTIONS)
    },
    {
        meta: {"id":"jane-eyre","title":"Jane Eyre","author":"Charlotte Brontë","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Smith, Elder, 1847 text","year":1847},"basis":"author-death-70","sourceSha256":"4628af159efb2510d12c1a6d5aff0b26b7961a239fbe8f2359e24d474c724750","payloadChecksum":"8376b37875d2650659c8bf76ac16e2b986f2d3be941902242d77a07a028c29ac","chars":1022262,"sections":40},
        load: () => import('./works/jane-eyre.js')
            .then(module => module.JANE_EYRE_SECTIONS)
    },
    {
        meta: {"id":"wuthering-heights","title":"Wuthering Heights","author":"Emily Brontë","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Thomas Cautley Newby, 1847","year":1847},"basis":"author-death-70","sourceSha256":"5e5d1c4a8081cfd4e8747e3aac821e64d0333398d73bd1300eafa1cb0ef0d817","payloadChecksum":"6fa0147f43ad71f1e6841a279da60a073b0c2553ff46e0fefe3155cd6716fb67","chars":645503,"sections":34},
        load: () => import('./works/wuthering-heights.js')
            .then(module => module.WUTHERING_HEIGHTS_SECTIONS)
    },
    {
        meta: {"id":"middlemarch","title":"Middlemarch","author":"George Eliot","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"publisher":"Standard Ebooks","year":1872},"basis":"pre-1930-us","payloadChecksum":"9b914fb44a2eeab62a47224e492037767c4478795dbc3651e2e77793da9a7ecd","chars":1773933,"sections":87,"structuredSource":"https://raw.githubusercontent.com/standardebooks/george-eliot_middlemarch"},
        load: () => import('./works/middlemarch.js')
            .then(module => module.MIDDLEMARCH_SECTIONS)
    },
    {
        meta: {"id":"the-brothers-karamazov","title":"The Brothers Karamazov","author":"Fyodor Dostoevsky","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"translator":"Constance Garnett","publisher":"Standard Ebooks","year":1880},"basis":"pre-1930-us","payloadChecksum":"bb6003f92da5abb6c3494bafc32fb8bb364b847ba6288fee7261f2ac3c0908d5","chars":1928256,"sections":96,"structuredSource":"https://raw.githubusercontent.com/standardebooks/fyodor-dostoevsky_the-brothers-karamazov_constance-garnett"},
        load: () => import('./works/the-brothers-karamazov.js')
            .then(module => module.THE_BROTHERS_KARAMAZOV_SECTIONS)
    },
    {
        meta: {"id":"crime-and-punishment","title":"Crime and Punishment","author":"Fyodor Dostoevsky","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Constance Garnett, Heinemann, 1914","year":1914},"basis":"pre-1930-us","sourceSha256":"eb2c76160c3976026be0b00745364f1cae43192614fed4b7f7868cda750d91e0","payloadChecksum":"a922afdad4c775914daccb1aecd7232c67e2857e992bc82a9e221a68e309af85","chars":1135010,"sections":41},
        load: () => import('./works/crime-and-punishment.js')
            .then(module => module.CRIME_AND_PUNISHMENT_SECTIONS)
    },
    {
        meta: {"id":"anna-karenina","title":"Anna Karenina","author":"Leo Tolstoy","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Constance Garnett, Heinemann, 1901","year":1901},"basis":"pre-1930-us","sourceSha256":"9055866091eac9d4dde11644f36198d7db6072abd10ff8df40b54ce4fbb124b0","payloadChecksum":"2a0bebafeabece61fc062d00d4a007a9cd299ad72a9e2d9b0ec898ccd373e97b","chars":1964539,"sections":239},
        load: () => import('./works/anna-karenina.js')
            .then(module => module.ANNA_KARENINA_SECTIONS)
    },
    {
        meta: {"id":"war-and-peace","title":"War and Peace","author":"Leo Tolstoy","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Louise and Aylmer Maude, Oxford University Press, 1922–23","year":1922},"basis":"pre-1930-us","sourceSha256":"799012088c944d7ab5b3f2a3837c6cafec9fd886058693bea8efe3a1f66c88cf","payloadChecksum":"449528ac5dd04df7025209e37196c333172d536677c823b4f12567f7ae45a8a1","chars":3205352,"sections":366},
        load: () => import('./works/war-and-peace.js')
            .then(module => module.WAR_AND_PEACE_SECTIONS)
    },
    {
        meta: {"id":"madame-bovary","title":"Madame Bovary","author":"Gustave Flaubert","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Eleanor Marx-Aveling, Vizetelly, 1886","year":1886},"basis":"author-death-70","sourceSha256":"9e39e8f8e9839f967396d5a1ebca25fc6af3eabe558f664d7994381ca39f637d","payloadChecksum":"8472dba5ad240ff022eea5f7dc4223f9ffc5bc792aeaa5fcaa958ca003d25db8","chars":652118,"sections":4},
        load: () => import('./works/madame-bovary.js')
            .then(module => module.MADAME_BOVARY_SECTIONS)
    },
    {
        meta: {"id":"the-scarlet-letter","title":"The Scarlet Letter","author":"Nathaniel Hawthorne","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Ticknor, Reed & Fields, 1850","year":1850},"basis":"author-death-70","sourceSha256":"9478fcee21dae3acdbea9f2fcc3ca46c84c2328c8771fad4a8ad0ac80a86ec47","payloadChecksum":"f1606ccbb321f26ff6e3afb37a8e64cb1382c1f77d3bea39aad84c5fbc09dc54","chars":480298,"sections":1},
        load: () => import('./works/the-scarlet-letter.js')
            .then(module => module.THE_SCARLET_LETTER_SECTIONS)
    },
    {
        meta: {"id":"mrs-dalloway","title":"Mrs Dalloway","author":"Virginia Woolf","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"Harcourt, Brace, New York, 1925","year":1925},"basis":"pre-1930-us","sourceSha256":"882c1827dad1c0b9c72333c8812dfbbb2dbccf55daa7a30e01b0d35226c5cad3","payloadChecksum":"8432ea21d074ebeb38662ac3e7eb7cea5c80183ef9969420679a1e5442699268","chars":361201,"sections":1},
        load: () => import('./works/mrs-dalloway.js')
            .then(module => module.MRS_DALLOWAY_SECTIONS)
    },
    {
        meta: {"id":"swann-s-way","title":"Swann's Way","author":"Marcel Proust","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"trans. C. K. Scott-Moncrieff, Chatto & Windus, 1922","year":1922},"basis":"pre-1930-us","sourceSha256":"08c9ac8abb2e5bb03d90f5e7c9383d127023ac493ea208e07f3b70291be2fb30","payloadChecksum":"bc21e5ac50acfdda24a4ec70f0666b8633a7a3738346e6269f6e5a7161ca1a8f","chars":1084831,"sections":1},
        load: () => import('./works/swann-s-way.js')
            .then(module => module.SWANN_S_WAY_SECTIONS)
    },
    {
        meta: {"id":"ulysses","title":"Ulysses","author":"James Joyce","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"imaginative","edition":{"publisher":"Standard Ebooks","year":1922},"basis":"pre-1930-us","payloadChecksum":"a6ab6eceb8db6943054846d278a8544d44e77e6eebd5e576b73469fbf5d41874","chars":1503705,"sections":18,"structuredSource":"https://raw.githubusercontent.com/standardebooks/james-joyce_ulysses"},
        load: () => import('./works/ulysses.js')
            .then(module => module.ULYSSES_SECTIONS)
    },
    {
        meta: {"id":"the-storm-of-steel","title":"The Storm of Steel","author":"Ernst Jünger; trans. Basil Creighton","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"literary","edition":{"statement":"Chatto & Windus, London, 1929; Basil Creighton translation","year":1929},"basis":"pre-1930-us","sourceSha256":"224f8df0945f5c2ae47ffb831d75fc3812f7d39bf35c246d860c14a9639e468e","payloadChecksum":"3fcac26f220da1719fa4011404b9d400272eced9bbcb85c30508c4273215afbc","chars":530738,"sections":2},
        load: () => import('./works/the-storm-of-steel.js')
            .then(module => module.THE_STORM_OF_STEEL_SECTIONS)
    },
    {
        meta: {"id":"the-ramayan-of-valmiki","title":"The Ramayan of Valmiki","author":"Valmiki, traditional attribution","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Ralph T. H. Griffith, 5 vols., 1870–74","year":1870},"basis":"author-death-70","sourceSha256":"b194c2cf6fc808525129ccf665f9bc2f9321e9e3e2e8fddf464fd3daa27de959","payloadChecksum":"f4a06be2031398eba6f0b34d856ef3fcc123717217e0b7f8e87655c6e4b51cfb","chars":2262759,"sections":495},
        load: () => import('./works/the-ramayan-of-valmiki.js')
            .then(module => module.THE_RAMAYAN_OF_VALMIKI_SECTIONS)
    },
    {
        meta: {"id":"the-mahabharata-of-krishna-dwaipayana-vyasa","title":"The Mahabharata of Krishna-Dwaipayana Vyasa","author":"Vyasa, traditional attribution","shelf":"eastern","traditionShelf":"eastern","subjectShelves":["form"],"division":"classical","edition":{"statement":"trans. Kisari Mohan Ganguli, 1883–96","year":1883},"basis":"author-death-70","sourceSha256":"879ed6f9d4a940e553ad1e498db8a1ce0f1b2a8b258dc5d84ad9164084ab6a05","payloadChecksum":"ca556b6230eeef4cb76fcdff68de0cb78ed31ca715a4dea998bf57356fd06e07","chars":17352337,"sections":1909},
        load: () => import('./works/the-mahabharata-of-krishna-dwaipayana-vyasa.js')
            .then(module => module.THE_MAHABHARATA_OF_KRISHNA_DWAIPAYANA_VYASA_SECTIONS)
    },
    {
        meta: {"id":"the-shahnama-of-firdausi","title":"The Shahnama of Firdausi","author":"Ferdowsi","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Arthur George Warner and Edmond Warner, 9 vols., Kegan Paul, 1905–25","year":1905},"basis":"pre-1930-us","sourceSha256":"26821042aef49b73e6cc335b78529120450253f1b109bf0cdd181f8eabe46833","payloadChecksum":"1f0643fab5eaf7e9bff2f82cc800f5e34c5de35ff544aea2dbada1c763ce8c43","chars":7219875,"sections":462},
        load: () => import('./works/the-shahnama-of-firdausi.js')
            .then(module => module.THE_SHAHNAMA_OF_FIRDAUSI_SECTIONS)
    },
    {
        meta: {"id":"the-book-of-the-thousand-nights-and-a-night","title":"The Book of the Thousand Nights and a Night","author":"anonymous Arabic/Persian tale tradition; trans. Richard F. Burton","shelf":"eastern","traditionShelf":"eastern","subjectShelves":["form"],"division":"classical","edition":{"statement":"Burton Club/Benares edition, 10 vols., text first issued 1885","year":1885},"basis":"author-death-70","sourceSha256":"b578a5b53ee4404ccef1f39cdd35b75257039d829301f4b7f53ceb2bcf9f6079","payloadChecksum":"a94da381336810af3f1f8e31068169cf8ee1eb9de55206794307fdfb8f22d84c","chars":9674655,"sections":35},
        load: () => import('./works/the-book-of-the-thousand-nights-and-a-night.js')
            .then(module => module.THE_BOOK_OF_THE_THOUSAND_NIGHTS_AND_A_NIGHT_SECTIONS)
    },
    {
        meta: {"id":"translations-of-shakuntala-and-other-works","title":"Translations of Shakuntala and Other Works","author":"Kalidasa","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Arthur W. Ryder, E. P. Dutton, 1912","year":1912},"basis":"pre-1930-us","sourceSha256":"8e415fe69e86f683c79f459dbc51b660971cf03da2d38343c43394acd67ea192","payloadChecksum":"be07a0d1e418acb40b6bc783364aa1f3758d90db502ccd81dafd9f5050a9e9ad","chars":390280,"sections":22},
        load: () => import('./works/translations-of-shakuntala-and-other-works.js')
            .then(module => module.TRANSLATIONS_OF_SHAKUNTALA_AND_OTHER_WORKS_SECTIONS)
    },
    {
        meta: {"id":"the-little-clay-cart","title":"The Little Clay Cart","author":"Shudraka, traditional attribution","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Arthur W. Ryder, Harvard Oriental Series, 1905","year":1905},"basis":"pre-1930-us","sourceSha256":"eb4ce380df70889ac69def97c8306c1349ae6e1499f19964a823ae239642fe39","payloadChecksum":"20af5fba3d8103a60dac62d3ca416e21b1a539efdb12c6ca5449de2c0a0c1ecd","chars":324562,"sections":16},
        load: () => import('./works/the-little-clay-cart.js')
            .then(module => module.THE_LITTLE_CLAY_CART_SECTIONS)
    },
    {
        meta: {"id":"twenty-two-goblins","title":"Twenty-Two Goblins","author":"traditional Sanskrit *Vetala* cycle; trans. Arthur W. Ryder","shelf":"eastern","traditionShelf":"eastern","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"University of Chicago Press, 1917","year":1917},"basis":"pre-1930-us","sourceSha256":"2b312b195c4ff331ed873d0cad6aed8e9d8c5bb8f76005a0a2d97d80f9111ed2","payloadChecksum":"3a695c8e11a97947f528c1e2d07aa0c1fa1b0d1ef60df7351fb4efdf6a8ff7e2","chars":216503,"sections":2},
        load: () => import('./works/twenty-two-goblins.js')
            .then(module => module.TWENTY_TWO_GOBLINS_SECTIONS)
    },
    {
        meta: {"id":"strange-stories-from-a-chinese-studio","title":"Strange Stories from a Chinese Studio","author":"Pu Songling","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Herbert A. Giles, revised 2 vols., 1908","year":1908},"basis":"pre-1930-us","sourceSha256":"bd457257d3a4ee562a18547b3aa7457a1e6d4358a953da9c177d47288e90e8f3","payloadChecksum":"e1538c84635b3eb6e584ff8678fdba9a31e2f47e4ece57510afc8792813ecb83","chars":1223384,"sections":3},
        load: () => import('./works/strange-stories-from-a-chinese-studio.js')
            .then(module => module.STRANGE_STORIES_FROM_A_CHINESE_STUDIO_SECTIONS)
    },
    {
        meta: {"id":"the-no-plays-of-japan","title":"The Nō Plays of Japan","author":"named and anonymous Noh dramatists; trans. Arthur Waley","shelf":"eastern","traditionShelf":"eastern","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"Alfred A. Knopf, New York, 1922","year":1922},"basis":"pre-1930-us","sourceSha256":"463f33a7b4fc1bb238878a870cce2273b11b4aa5484fbeeeb873d7d8170db6d1","payloadChecksum":"4b2ae682cd4d7835b9f353ac85f7eed4c9e3202fab909362a2e85ca44f4d7458","chars":322118,"sections":14},
        load: () => import('./works/the-no-plays-of-japan.js')
            .then(module => module.THE_NO_PLAYS_OF_JAPAN_SECTIONS)
    },
    {
        meta: {"id":"a-hundred-and-seventy-chinese-poems","title":"A Hundred and Seventy Chinese Poems","author":"named Chinese poets; trans. Arthur Waley","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"Alfred A. Knopf, New York, 1919 (London first ed. 1918)","year":1919},"basis":"pre-1930-us","sourceSha256":"9140e55f7e1523f6075d8464445a1dc49f17a4851d53bd89333883e08a0d390d","payloadChecksum":"51ed76c62d4bd496e92ac3460846a52c13a5a1c1125cddf8e2f9c49c8aa4fa3d","chars":199884,"sections":14},
        load: () => import('./works/a-hundred-and-seventy-chinese-poems.js')
            .then(module => module.A_HUNDRED_AND_SEVENTY_CHINESE_POEMS_SECTIONS)
    },
    {
        meta: {"id":"the-shih-king-or-book-of-poetry","title":"The Shih King, or Book of Poetry","author":"anonymous early Chinese poets; trans. James Legge","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"classical","edition":{"statement":"*Sacred Books of the East*, vol. 3, Clarendon Press, 1879","year":1879},"basis":"author-death-70","sourceSha256":"29ae404c43edd4c107e13b7acb0e9a8dd44b8f9a80eaa0f3128052fd6eef9569","payloadChecksum":"0c21f35788836aaf5de8e75cc53d3f7c689337111886aad4009db84b85bea4ef","chars":303694,"sections":102},
        load: () => import('./works/the-shih-king-or-book-of-poetry.js')
            .then(module => module.THE_SHIH_KING_OR_BOOK_OF_POETRY_SECTIONS)
    },
    {
        meta: {"id":"a-hundred-verses-from-old-japan","title":"A Hundred Verses from Old Japan","author":"the *Hyakunin Isshu* poets; trans. William N. Porter","shelf":"eastern","traditionShelf":"eastern","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"Clarendon Press, 1909","year":1909},"basis":"author-death-70","sourceSha256":"25c08053de411cbb2ecac02ead8935c207990ec6867dabbab27464ad51522bf6","payloadChecksum":"de3061632d1654abb0222644840002eff3ed5c0bfa0e9aa0ad790cd86e274d96","chars":111771,"sections":11},
        load: () => import('./works/a-hundred-verses-from-old-japan.js')
            .then(module => module.A_HUNDRED_VERSES_FROM_OLD_JAPAN_SECTIONS)
    },
    {
        meta: {"id":"kwaidan-stories-and-studies-of-strange-things","title":"Kwaidan: Stories and Studies of Strange Things","author":"Lafcadio Hearn","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"Houghton, Mifflin, Boston/New York, 1904","year":1904},"basis":"pre-1930-us","sourceSha256":"46f3fa0f2104f69b25331c256dc1b8280d610b5918389d4accf1641ada2b0fa0","payloadChecksum":"8aa97ceb9f956be02efa24fe01303974c91c6a83f640a0f6dd546dcb38f5f999","chars":211619,"sections":4},
        load: () => import('./works/kwaidan-stories-and-studies-of-strange-things.js')
            .then(module => module.KWAIDAN_STORIES_AND_STUDIES_OF_STRANGE_THINGS_SECTIONS)
    },
    {
        meta: {"id":"the-gulistan-or-rose-garden-of-sa-di","title":"The Gulistan; or, Rose Garden of Sa'di","author":"Sa'di","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Edward Rehatsek, 1888","year":1888},"basis":"author-death-70","sourceSha256":"6e61d2862eb3eeca8136d239443edc7c9ab33fea608f04d9b333a0c337641ca3","payloadChecksum":"0d5fbf5dae3dd33b3b2af2ac45e2dee2696f8e64fe3a61a4dd9a29f97fb3d6d1","chars":245281,"sections":11},
        load: () => import('./works/the-gulistan-or-rose-garden-of-sa-di.js')
            .then(module => module.THE_GULISTAN_OR_ROSE_GARDEN_OF_SA_DI_SECTIONS)
    },
    {
        meta: {"id":"rubaiyat-of-omar-khayyam","title":"Rubáiyát of Omar Khayyám","author":"Omar Khayyam, attributed corpus; trans. Edward FitzGerald","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"FitzGerald's four principal editions, 1859–79, with variants","year":1859},"basis":"author-death-70","sourceSha256":"df3aa2528824ee0c39c9a3355e4622d81179395d3d79cbacc9dc3b39fa45e309","payloadChecksum":"a3651ee23fed9e69f34e59d86639ab9953b70cc310fc2e9dcf1607c1b84e1537","chars":68360,"sections":1},
        load: () => import('./works/rubaiyat-of-omar-khayyam.js')
            .then(module => module.RUBAIYAT_OF_OMAR_KHAYYAM_SECTIONS)
    },
    {
        meta: {"id":"romance-of-the-three-kingdoms","title":"Romance of the Three Kingdoms","author":"Luo Guanzhong, traditional attribution","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. C. H. Brewitt-Taylor, Kelly & Walsh, Shanghai, 2 vols., 1925; scan-backed Wikisource [vol. I](https://en.wikisource.org/wiki/File:Romance_of_the_Three_Kingdoms_-_tr._Brewitt-Taylor_-_Volume_1.djvu) and [vol. II](https://en.wikisource.org/wiki/File:Romance_of_the_Three_Kingdoms_-_tr._Brewitt-Taylor_-_Volume_2.djvu); `author-death-70`","year":1925},"basis":"author-death-70","sourceSha256":"7cff2d01cfc02c21232a8bb80f7a2cb17ca8a6a72f23174a9bbc28ed3cae6170","payloadChecksum":"093b2ab6768b6dc6b0da238e43d5184c87c2a089ffa064ff271bd149c8c9dba2","chars":3073662,"sections":126},
        load: () => import('./works/romance-of-the-three-kingdoms.js')
            .then(module => module.ROMANCE_OF_THE_THREE_KINGDOMS_SECTIONS)
    }
];
