/** GENERATED by scripts/literature-ingest.mjs; do not hand-edit. */
export const LITERATURE_WORKS = [
    {
        meta: {"id":"the-iliad","title":"The Iliad","author":"Homer","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Andrew Lang, Walter Leaf, and Ernest Myers, 1883","year":1883},"basis":"author-death-70","sourceSha256":"4da9875af465f2ca8096b5f8d29d6dcf2e83b734afdf08ca7cb41f81cfb9c54d","payloadChecksum":"49862f79d02fc2ffaf4fa20d90d666d643d87ffa72e3a9da9ca4b4a4e0778270","chars":856336,"sections":43},
        load: () => import('./works/the-iliad.js')
            .then(module => module.THE_ILIAD_SECTIONS)
    },
    {
        meta: {"id":"the-odyssey","title":"The Odyssey","author":"Homer","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Samuel Butler, Longmans, Green, 1900","year":1900},"basis":"pre-1930-us","sourceSha256":"ca2ebb58066e0e40c42e1e149b7079f392f6790c2bf5babea262459961b3b90f","payloadChecksum":"c0a916683004372896ebe31da22062accb7940c49e2d387f349416f7ae9104b9","chars":677227,"sections":41},
        load: () => import('./works/the-odyssey.js')
            .then(module => module.THE_ODYSSEY_SECTIONS)
    },
    {
        meta: {"id":"the-aeneid","title":"The Aeneid","author":"Virgil","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. John Dryden, 1697","year":1697},"basis":"author-death-70","sourceSha256":"a7f04d408682906c73d833b71ed2e89f1e2b752a33c2c36975d260c3427b1d87","payloadChecksum":"dab62a28a7eedeff5cfd38c58a9e76cd2e71ab2bec56b87c3d9a0d58f3eee3a8","chars":696177,"sections":18},
        load: () => import('./works/the-aeneid.js')
            .then(module => module.THE_AENEID_SECTIONS)
    },
    {
        meta: {"id":"metamorphoses","title":"Metamorphoses","author":"Ovid","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Brookes More, Cornhill Publishing/Four Seas, Boston, 1922","year":1922},"basis":"pre-1930-us","sourceSha256":"618f01b1564edb08a9983e74cadcf36446eec84d6575cd224b561853dd3889f3","payloadChecksum":"9f410e4a44da5324742ed2f4987005fd38b91e797d27476b373b42e6b8cf7796","chars":756379,"sections":19},
        load: () => import('./works/metamorphoses.js')
            .then(module => module.METAMORPHOSES_SECTIONS)
    },
    {
        meta: {"id":"beowulf","title":"Beowulf","author":"anonymous","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Francis B. Gummere, 1910","year":1910},"basis":"pre-1930-us","sourceSha256":"dacf2aaac91ccece3112decd297ce8c9ff54bc6f6b140bcfe26abdf23a73e7a9","payloadChecksum":"cbcc1dc373274064f2c95f34317ee7cc5fab41ceaf408c809f4a28498f8fbd99","chars":147049,"sections":5},
        load: () => import('./works/beowulf.js')
            .then(module => module.BEOWULF_SECTIONS)
    },
    {
        meta: {"id":"the-divine-comedy","title":"The Divine Comedy","author":"Dante Alighieri","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"classical","edition":{"statement":"trans. Henry Wadsworth Longfellow, 1867","year":1867},"basis":"author-death-70","sourceSha256":"ca86a10779330beab7481d7965c1080d694a6f6569b127199b9225a813a176b6","payloadChecksum":"e3e9c285c6d8e7b07b55e8980d973563ebe3f11c80042d006eca77590542628f","chars":219212,"sections":5},
        load: () => import('./works/the-divine-comedy.js')
            .then(module => module.THE_DIVINE_COMEDY_SECTIONS)
    },
    {
        meta: {"id":"the-nibelungenlied","title":"The Nibelungenlied","author":"anonymous","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Daniel B. Shumway, Houghton Mifflin, 1909","year":1909},"basis":"pre-1930-us","sourceSha256":"8c5d2e1244ef2a1b1f1a64f63ec98f99c500703e00f00480e8045f80ce7bb833","payloadChecksum":"b1511530485b76922828d1d01d1f69e59f99135d5145ad8bc998641878d62e80","chars":564779,"sections":61},
        load: () => import('./works/the-nibelungenlied.js')
            .then(module => module.THE_NIBELUNGENLIED_SECTIONS)
    },
    {
        meta: {"id":"the-song-of-roland","title":"The Song of Roland","author":"anonymous","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. C. K. Scott-Moncrieff, Chapman & Hall, 1919","year":1919},"basis":"pre-1930-us","sourceSha256":"b2c4ca23656b8dad4c6f03087b5b4eb2eb90b727f7a2533757ab7322eb3ffa60","payloadChecksum":"9fb6a8b59e0bed7a86fa79ece650830f1385583f07e4f93fa3b84e7eb96b6534","chars":191987,"sections":6},
        load: () => import('./works/the-song-of-roland.js')
            .then(module => module.THE_SONG_OF_ROLAND_SECTIONS)
    },
    {
        meta: {"id":"the-kalevala","title":"The Kalevala","author":"traditional singers; compiled by Elias Lönnrot","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. John Martin Crawford, 2 vols., 1888","year":1888},"basis":"author-death-70","sourceSha256":"04215ac4c7c559f85cd350649edf2454e37814721fd6cc38deafc43ca4f52d94","payloadChecksum":"a3f91c7aa35a59d9c856040ce8d3ffb291b43dbac54824220221758a35cf3b8f","chars":813763,"sections":61},
        load: () => import('./works/the-kalevala.js')
            .then(module => module.THE_KALEVALA_SECTIONS)
    },
    {
        meta: {"id":"the-canterbury-tales-and-other-poems","title":"The Canterbury Tales and Other Poems","author":"Geoffrey Chaucer","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"classical","edition":{"statement":"ed. D. Laing Purves, 1870","year":1870},"basis":"author-death-70","sourceSha256":"1b9e54bb090b3c9d7dbcd6e6130707f6b43da41feaf080c6d607217bf15d4802","payloadChecksum":"3200a9c70fb8c32e7e3d566a83e9d660b985997119e198a99928536a6c35f4c0","chars":1647839,"sections":61},
        load: () => import('./works/the-canterbury-tales-and-other-poems.js')
            .then(module => module.THE_CANTERBURY_TALES_AND_OTHER_POEMS_SECTIONS)
    },
    {
        meta: {"id":"le-morte-darthur","title":"Le Morte Darthur","author":"Sir Thomas Malory","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"Everyman's Library ed. Ernest Rhys, 1906","year":1906},"basis":"pre-1930-us","sourceSha256":"1e0eff52571d91782904eca13fbfcdcf32d1cb043c52e0610036fd6012eefd2d","payloadChecksum":"11da9563607311e878180692035a02e2bb1cb2e7252d2635b472c2617500b2c9","chars":1848814,"sections":595},
        load: () => import('./works/le-morte-darthur.js')
            .then(module => module.LE_MORTE_DARTHUR_SECTIONS)
    },
    {
        meta: {"id":"the-decameron","title":"The Decameron","author":"Giovanni Boccaccio","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"classical","edition":{"statement":"trans. John Payne, 1886","year":1886},"basis":"author-death-70","sourceSha256":"e9928094dcca57ddf06ab06b4026f59d1cff2ee3cde3e2fac53f6068b3af0c51","payloadChecksum":"f9ad5a2593703f776971192362b42d28745e3a3957e53fb7b81da8b2cf533398","chars":1694855,"sections":113},
        load: () => import('./works/the-decameron.js')
            .then(module => module.THE_DECAMERON_SECTIONS)
    },
    {
        meta: {"id":"the-house-of-atreus","title":"The House of Atreus","author":"Aeschylus","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"classical","edition":{"statement":"trans. E. D. A. Morshead, 1881","year":1881},"basis":"author-death-70","sourceSha256":"ac6d92adc14a502568dcad9cefeba6121bb8d400f696cf31a243d810d3215ce4","payloadChecksum":"f1309d7d9605ba95cf046f6ae76d9f4f6d60cf233353da09d8bb39de9a3bb8e6","chars":137057,"sections":8},
        load: () => import('./works/the-house-of-atreus.js')
            .then(module => module.THE_HOUSE_OF_ATREUS_SECTIONS)
    },
    {
        meta: {"id":"the-oedipus-trilogy","title":"The Oedipus Trilogy","author":"Sophocles","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Francis Storr, Loeb Classical Library, 1912","year":1912},"basis":"pre-1930-us","sourceSha256":"3a5c1d02a04e5743df141bf0ca3480ab3774a9713846522921814d7cd65d7562","payloadChecksum":"e9fc8c8766f80bc8c8b0de00eeba50e7050ca5be4fdcdd9fb68950ad6045bb9b","chars":214579,"sections":4},
        load: () => import('./works/the-oedipus-trilogy.js')
            .then(module => module.THE_OEDIPUS_TRILOGY_SECTIONS)
    },
    {
        meta: {"id":"the-bacchae","title":"The Bacchae","author":"Euripides","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Gilbert Murray, 2nd ed., George Allen, 1906","year":1906},"basis":"author-death-70","sourceSha256":"a7409c885b019b3e8111e6e59530d3c33f08cb57224a2ff9e6464175da8f1140","payloadChecksum":"f1f407b57d112675ff97d728f58ab2c68e520e720546993c81cc10e89aa08078","chars":109868,"sections":2},
        load: () => import('./works/the-bacchae.js')
            .then(module => module.THE_BACCHAE_SECTIONS)
    },
    {
        meta: {"id":"hamlet","title":"Hamlet","author":"William Shakespeare","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Cambridge Shakespeare, ed. W. G. Clark and W. Aldis Wright, 1863–66","year":1863},"basis":"author-death-70","sourceSha256":"7b0dcbe9e291d018f1755e7b5384d188bd705192a1fe0cc62ce47333f68db0eb","payloadChecksum":"518fdc6fd9d78ec0896d532f927ed2664dc19b51962ad0984f39a42eb0f41940","chars":561477,"sections":95},
        load: () => import('./works/hamlet.js')
            .then(module => module.HAMLET_SECTIONS)
    },
    {
        meta: {"id":"king-lear","title":"King Lear","author":"William Shakespeare","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Cambridge Shakespeare, ed. Clark and Wright, 1863–66","year":1863},"basis":"author-death-70","sourceSha256":"7b0dcbe9e291d018f1755e7b5384d188bd705192a1fe0cc62ce47333f68db0eb","payloadChecksum":"606bc2f4c7cbdc7b503dbe1086eff62df74d90508c66a91e0e8053958cf2af01","chars":423520,"sections":99},
        load: () => import('./works/king-lear.js')
            .then(module => module.KING_LEAR_SECTIONS)
    },
    {
        meta: {"id":"the-tempest","title":"The Tempest","author":"William Shakespeare","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Cambridge Shakespeare, ed. Clark and Wright, 1863–66","year":1863},"basis":"author-death-70","sourceSha256":"6387ed27885f9ee6c0b920edf7e7ce2311728acc98a9331c84952ed63ceb1227","payloadChecksum":"6c84f2c16e74f7a673092f67b841bcf0eb92df1c5c33189f31e93a5cc54973b7","chars":154996,"sections":50},
        load: () => import('./works/the-tempest.js')
            .then(module => module.THE_TEMPEST_SECTIONS)
    },
    {
        meta: {"id":"the-tragical-history-of-doctor-faustus","title":"The Tragical History of Doctor Faustus","author":"Christopher Marlowe","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Alexander Dyce text of the 1604 A-text, 1870s","year":1604},"basis":"author-death-70","sourceSha256":"a60b48ff5483f8b62710b5d77b545c0ef2c97f077f519d277ee0279556362ebc","payloadChecksum":"1a3310f9645ac0fcc193b99dfbc005485b5b0fad33052c41b08f9d08eaf1a636","chars":124196,"sections":3},
        load: () => import('./works/the-tragical-history-of-doctor-faustus.js')
            .then(module => module.THE_TRAGICAL_HISTORY_OF_DOCTOR_FAUSTUS_SECTIONS)
    },
    {
        meta: {"id":"the-duchess-of-malfi","title":"The Duchess of Malfi","author":"John Webster","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Harvard Classics-era public-domain text","year":null},"basis":"author-death-70","sourceSha256":"18e701cec034a9b0ebe7b4d8d1513963ecbea9f58a641750aef49319ed78a29c","payloadChecksum":"e75545c6fb43efc55815240768a6074a6cfbc8ba88357f8bf2d946676c9ace43","chars":168424,"sections":20},
        load: () => import('./works/the-duchess-of-malfi.js')
            .then(module => module.THE_DUCHESS_OF_MALFI_SECTIONS)
    },
    {
        meta: {"id":"phaedra","title":"Phaedra","author":"Jean Racine","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Robert Bruce Boswell, in *The French Classical Romances*, 1899","year":1899},"basis":"author-death-70","sourceSha256":"3a8b10eff0303cfb76c6133bbd434502ea3dfc3b7b39590b5f103fbacdfbed67","payloadChecksum":"3eabebaef21434ec4953bb50114e6fdaf5cadbbb60b9cc6e8f97b22f723a77c1","chars":97050,"sections":31},
        load: () => import('./works/phaedra.js')
            .then(module => module.PHAEDRA_SECTIONS)
    },
    {
        meta: {"id":"faust","title":"Faust","author":"Johann Wolfgang von Goethe","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Bayard Taylor, 2 vols., 1870–71; Boston/New York Houghton Mifflin reissue, 1912","year":1870},"basis":"pre-1930-us","sourceSha256":"29b63eca043b81d6d25b9169c7e3fe0a0cb4c510f5aa830d1ebedff2527be46e","payloadChecksum":"09e4fe50ccd6830166cb99fffc8e0a882faf2cab1f931eced36759c25971f6e1","chars":868047,"sections":60},
        load: () => import('./works/faust.js')
            .then(module => module.FAUST_SECTIONS)
    },
    {
        meta: {"id":"a-doll-s-house","title":"A Doll's House","author":"Henrik Ibsen","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. William Archer, 1889","year":1889},"basis":"author-death-70","sourceSha256":"11003afc47b90b4668d9fefc2f7cfe81c5457f08aa6347041d1d8f629bdcaff0","payloadChecksum":"27511161c4c6a88743bfb2dcd2fc6f56bf19f5499602bc5d99b117651768f3b2","chars":141994,"sections":8},
        load: () => import('./works/a-doll-s-house.js')
            .then(module => module.A_DOLL_S_HOUSE_SECTIONS)
    },
    {
        meta: {"id":"don-quixote","title":"Don Quixote","author":"Miguel de Cervantes","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"trans. John Ormsby, 1885","year":1885},"basis":"author-death-70","sourceSha256":"b11a0b182413f1dea386343f10563b851dc905c6d649f636276afd237a2fdf8a","payloadChecksum":"339c1b8f0895c82de89cea1d94cec4a4bb14d61d7a60a11582496f47731abdb5","chars":2290805,"sections":220},
        load: () => import('./works/don-quixote.js')
            .then(module => module.DON_QUIXOTE_SECTIONS)
    },
    {
        meta: {"id":"paradise-lost","title":"Paradise Lost","author":"John Milton","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"1674 twelve-book text","year":1674},"basis":"author-death-70","sourceSha256":"5d10e31d4f2ac7be187d4454a6bd612bc649bd4cfdcbf0c97fc811a496cd39e9","payloadChecksum":"f0678c3d5fc2e835518f6d79e1c8d3981460e9ab2dd19d0156175ba89f288d23","chars":455944,"sections":24},
        load: () => import('./works/paradise-lost.js')
            .then(module => module.PARADISE_LOST_SECTIONS)
    },
    {
        meta: {"id":"the-faerie-queene","title":"The Faerie Queene","author":"Edmund Spenser","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"ed. John W. Hales, Everyman's Library, 2 vols., J. M. Dent/E. P. Dutton, London/New York, 1909; Internet Archive [vol. I `faeriequeenedis01spen`](https://archive.org/details/faeriequeenedis01spen) and [vol. II `faeriequeenedis02spen`](https://archive.org/details/faeriequeenedis02spen); `pre-1930-us`","year":1909},"basis":"pre-1930-us","sourceSha256":"af7a180072f167953c4c45bdddd2e694a14c67da6770eb0cfb205f075cd77ea9","payloadChecksum":"896520138de4b850337b4099259f232982be893d432fbaea888869f4727ffe5b","chars":2036477,"sections":519},
        load: () => import('./works/the-faerie-queene.js')
            .then(module => module.THE_FAERIE_QUEENE_SECTIONS)
    },
    {
        meta: {"id":"the-troubadours","title":"The Troubadours","author":"named Occitan poets; translated and discussed by H. J. Chaytor","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Cambridge University Press, 1912","year":1912},"basis":"pre-1930-us","sourceSha256":"04b1ed51f9d92fc2b4f993b465410fa0ce994a8b50042ac35d46d0db04ee4b91","payloadChecksum":"c79d0cd32cf835244708cf2e2fd43dfd9c1b83c164d4a68b3c9e9aba29cc3cff","chars":198090,"sections":35},
        load: () => import('./works/the-troubadours.js')
            .then(module => module.THE_TROUBADOURS_SECTIONS)
    },
    {
        meta: {"id":"moby-dick-or-the-whale","title":"Moby-Dick; or, The Whale","author":"Herman Melville","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"Harper & Brothers, New York, 1851","year":1851},"basis":"author-death-70","sourceSha256":"22acc42134f30ad8612f55fcf17d83e802adfe169c99c0663c1f211a1dacfb80","payloadChecksum":"021996243e0738f30ec0f1413437b6f409b7c60ffa30338fb290b03240cf3672","chars":1206293,"sections":199},
        load: () => import('./works/moby-dick-or-the-whale.js')
            .then(module => module.MOBY_DICK_OR_THE_WHALE_SECTIONS)
    },
    {
        meta: {"id":"pride-and-prejudice","title":"Pride and Prejudice","author":"Jane Austen","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"1813 text","year":1813},"basis":"author-death-70","sourceSha256":"84da0929bbf56fbabf3be812964d2a0384e08915dcefa896f560d5ea8a71f5d8","payloadChecksum":"54e6bb58876940dce8b8aeee9d369fdc2e5322c6a6792ef1a6edd018131a01f8","chars":726141,"sections":85},
        load: () => import('./works/pride-and-prejudice.js')
            .then(module => module.PRIDE_AND_PREJUDICE_SECTIONS)
    },
    {
        meta: {"id":"jane-eyre","title":"Jane Eyre","author":"Charlotte Brontë","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Smith, Elder, 1847 text","year":1847},"basis":"author-death-70","sourceSha256":"4628af159efb2510d12c1a6d5aff0b26b7961a239fbe8f2359e24d474c724750","payloadChecksum":"1e82ef163e32c329c94464a33ee16d3e85bce021201e234a3bd86b80dc420486","chars":1019803,"sections":67},
        load: () => import('./works/jane-eyre.js')
            .then(module => module.JANE_EYRE_SECTIONS)
    },
    {
        meta: {"id":"wuthering-heights","title":"Wuthering Heights","author":"Emily Brontë","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Thomas Cautley Newby, 1847","year":1847},"basis":"author-death-70","sourceSha256":"5e5d1c4a8081cfd4e8747e3aac821e64d0333398d73bd1300eafa1cb0ef0d817","payloadChecksum":"d3b1114162aa10676fe160b900e8ea4005ff5fc449733867e7eb131816b03382","chars":643875,"sections":50},
        load: () => import('./works/wuthering-heights.js')
            .then(module => module.WUTHERING_HEIGHTS_SECTIONS)
    },
    {
        meta: {"id":"middlemarch","title":"Middlemarch","author":"George Eliot","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"William Blackwood, 1871–72","year":1871},"basis":"author-death-70","sourceSha256":"c87a06177bd977f76ef925b7fb762104d7590edbdcb095033ab657d993ff6bc3","payloadChecksum":"a6483814db083faecb299a2e5be96349ccf586d3ca5ef614d703076c41c3d710","chars":1774701,"sections":126},
        load: () => import('./works/middlemarch.js')
            .then(module => module.MIDDLEMARCH_SECTIONS)
    },
    {
        meta: {"id":"the-brothers-karamazov","title":"The Brothers Karamazov","author":"Fyodor Dostoevsky","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Constance Garnett, Macmillan, 1912","year":1912},"basis":"pre-1930-us","sourceSha256":"e75dccb79871811ec93db160d473d05049c7af12a501a74b4be4ec01299c84b7","payloadChecksum":"456047f2a8c7e77766b33d557693503b72d875b75b8678acd8ba12b688b61963","chars":1926691,"sections":138},
        load: () => import('./works/the-brothers-karamazov.js')
            .then(module => module.THE_BROTHERS_KARAMAZOV_SECTIONS)
    },
    {
        meta: {"id":"crime-and-punishment","title":"Crime and Punishment","author":"Fyodor Dostoevsky","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Constance Garnett, Heinemann, 1914","year":1914},"basis":"pre-1930-us","sourceSha256":"eb2c76160c3976026be0b00745364f1cae43192614fed4b7f7868cda750d91e0","payloadChecksum":"b5cdffd916d4cf9e7238f1b2e57d8119473517a7833dac109ab5bb46a146e4d2","chars":1132861,"sections":65},
        load: () => import('./works/crime-and-punishment.js')
            .then(module => module.CRIME_AND_PUNISHMENT_SECTIONS)
    },
    {
        meta: {"id":"anna-karenina","title":"Anna Karenina","author":"Leo Tolstoy","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Constance Garnett, Heinemann, 1901","year":1901},"basis":"pre-1930-us","sourceSha256":"9055866091eac9d4dde11644f36198d7db6072abd10ff8df40b54ce4fbb124b0","payloadChecksum":"781d082cc96f4824e3c8eab0191aee381df8065927c0d7012b2433cf8704b192","chars":1959106,"sections":277},
        load: () => import('./works/anna-karenina.js')
            .then(module => module.ANNA_KARENINA_SECTIONS)
    },
    {
        meta: {"id":"war-and-peace","title":"War and Peace","author":"Leo Tolstoy","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Louise and Aylmer Maude, Oxford University Press, 1922–23","year":1922},"basis":"pre-1930-us","sourceSha256":"799012088c944d7ab5b3f2a3837c6cafec9fd886058693bea8efe3a1f66c88cf","payloadChecksum":"97c14e07a6e443f1f80994e0cd27d3cc04e941383cb3f11fe9bd6c51cc28749b","chars":3190387,"sections":445},
        load: () => import('./works/war-and-peace.js')
            .then(module => module.WAR_AND_PEACE_SECTIONS)
    },
    {
        meta: {"id":"madame-bovary","title":"Madame Bovary","author":"Gustave Flaubert","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Eleanor Marx-Aveling, Vizetelly, 1886","year":1886},"basis":"author-death-70","sourceSha256":"9e39e8f8e9839f967396d5a1ebca25fc6af3eabe558f664d7994381ca39f637d","payloadChecksum":"76459afe6b7587ffae21d22d6ecd4ff8344b0781f00ce24fb9a82b8004c2ab2e","chars":650271,"sections":54},
        load: () => import('./works/madame-bovary.js')
            .then(module => module.MADAME_BOVARY_SECTIONS)
    },
    {
        meta: {"id":"the-scarlet-letter","title":"The Scarlet Letter","author":"Nathaniel Hawthorne","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"imaginative","edition":{"statement":"Ticknor, Reed & Fields, 1850","year":1850},"basis":"author-death-70","sourceSha256":"9478fcee21dae3acdbea9f2fcc3ca46c84c2328c8771fad4a8ad0ac80a86ec47","payloadChecksum":"bac7e359c3d2d510eaf57f0c63a607812dbacb6d54ccb0979c672f105dae7b89","chars":478987,"sections":21},
        load: () => import('./works/the-scarlet-letter.js')
            .then(module => module.THE_SCARLET_LETTER_SECTIONS)
    },
    {
        meta: {"id":"mrs-dalloway","title":"Mrs Dalloway","author":"Virginia Woolf","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"Harcourt, Brace, New York, 1925","year":1925},"basis":"pre-1930-us","sourceSha256":"882c1827dad1c0b9c72333c8812dfbbb2dbccf55daa7a30e01b0d35226c5cad3","payloadChecksum":"3124e2cf183f92dc35bfc209336552c8eefff790fcf758315981ef4bdd2b6935","chars":360583,"sections":10},
        load: () => import('./works/mrs-dalloway.js')
            .then(module => module.MRS_DALLOWAY_SECTIONS)
    },
    {
        meta: {"id":"swann-s-way","title":"Swann's Way","author":"Marcel Proust","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"trans. C. K. Scott-Moncrieff, Chatto & Windus, 1922","year":1922},"basis":"pre-1930-us","sourceSha256":"08c9ac8abb2e5bb03d90f5e7c9383d127023ac493ea208e07f3b70291be2fb30","payloadChecksum":"24b021c8e3db71641c6a728b61f885d1494a754bde8ca0c56af4eae0bc2a469e","chars":1081726,"sections":45},
        load: () => import('./works/swann-s-way.js')
            .then(module => module.SWANN_S_WAY_SECTIONS)
    },
    {
        meta: {"id":"ulysses","title":"Ulysses","author":"James Joyce","shelf":"western","traditionShelf":"western","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"Shakespeare and Company, Paris, 2 February 1922","year":1922},"basis":"pre-1930-us","sourceSha256":"03ac6fcc703729ac5eb59c11e98da434377bc61be3893c7367496dc7191f3564","payloadChecksum":"15b1e61cf28e9d6cdc369010ae1515772eea6e04a2e3061a5db0bb731abb5011","chars":1515836,"sections":66},
        load: () => import('./works/ulysses.js')
            .then(module => module.ULYSSES_SECTIONS)
    },
    {
        meta: {"id":"the-storm-of-steel","title":"The Storm of Steel","author":"Ernst Jünger; trans. Basil Creighton","shelf":"western","traditionShelf":"western","subjectShelves":[],"division":"literary","edition":{"statement":"Chatto & Windus, London, 1929; Basil Creighton translation","year":1929},"basis":"pre-1930-us","sourceSha256":"224f8df0945f5c2ae47ffb831d75fc3812f7d39bf35c246d860c14a9639e468e","payloadChecksum":"fea2e159f3c9c58f88853acbe863c38bd5987447db8be8977c449d9df75aebee","chars":528985,"sections":37},
        load: () => import('./works/the-storm-of-steel.js')
            .then(module => module.THE_STORM_OF_STEEL_SECTIONS)
    },
    {
        meta: {"id":"the-ramayan-of-valmiki","title":"The Ramayan of Valmiki","author":"Valmiki, traditional attribution","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Ralph T. H. Griffith, 5 vols., 1870–74","year":1870},"basis":"author-death-70","sourceSha256":"b194c2cf6fc808525129ccf665f9bc2f9321e9e3e2e8fddf464fd3daa27de959","payloadChecksum":"96602a6246e0d31a9b4896243b69f3cb164c53f50fff87045f376fa9ce3074cd","chars":2230205,"sections":527},
        load: () => import('./works/the-ramayan-of-valmiki.js')
            .then(module => module.THE_RAMAYAN_OF_VALMIKI_SECTIONS)
    },
    {
        meta: {"id":"the-mahabharata-of-krishna-dwaipayana-vyasa","title":"The Mahabharata of Krishna-Dwaipayana Vyasa","author":"Vyasa, traditional attribution","shelf":"eastern","traditionShelf":"eastern","subjectShelves":["form"],"division":"classical","edition":{"statement":"trans. Kisari Mohan Ganguli, 1883–96","year":1883},"basis":"author-death-70","sourceSha256":"879ed6f9d4a940e553ad1e498db8a1ce0f1b2a8b258dc5d84ad9164084ab6a05","payloadChecksum":"edbfc1ac5413972d578c751b14dc0479c8c07fdd8b7968fe36a62ee0a0f5e2d2","chars":17301102,"sections":2264},
        load: () => import('./works/the-mahabharata-of-krishna-dwaipayana-vyasa.js')
            .then(module => module.THE_MAHABHARATA_OF_KRISHNA_DWAIPAYANA_VYASA_SECTIONS)
    },
    {
        meta: {"id":"the-shahnama-of-firdausi","title":"The Shahnama of Firdausi","author":"Ferdowsi","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Arthur George Warner and Edmond Warner, 9 vols., Kegan Paul, 1905–25","year":1905},"basis":"pre-1930-us","sourceSha256":"26821042aef49b73e6cc335b78529120450253f1b109bf0cdd181f8eabe46833","payloadChecksum":"46035c45b2359aed8beeacc2dcc8c8b39292e522e311b98ae1b0c2ef7fd8fa17","chars":7200747,"sections":730},
        load: () => import('./works/the-shahnama-of-firdausi.js')
            .then(module => module.THE_SHAHNAMA_OF_FIRDAUSI_SECTIONS)
    },
    {
        meta: {"id":"the-book-of-the-thousand-nights-and-a-night","title":"The Book of the Thousand Nights and a Night","author":"anonymous Arabic/Persian tale tradition; trans. Richard F. Burton","shelf":"eastern","traditionShelf":"eastern","subjectShelves":["form"],"division":"classical","edition":{"statement":"Burton Club/Benares edition, 10 vols., text first issued 1885","year":1885},"basis":"author-death-70","sourceSha256":"b578a5b53ee4404ccef1f39cdd35b75257039d829301f4b7f53ceb2bcf9f6079","payloadChecksum":"dda6605fa4bf2aa69e0a78c6595f9749353f0455c37c3183e4a8cda4fb215bb2","chars":9636122,"sections":616},
        load: () => import('./works/the-book-of-the-thousand-nights-and-a-night.js')
            .then(module => module.THE_BOOK_OF_THE_THOUSAND_NIGHTS_AND_A_NIGHT_SECTIONS)
    },
    {
        meta: {"id":"translations-of-shakuntala-and-other-works","title":"Translations of Shakuntala and Other Works","author":"Kalidasa","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"classical","edition":{"statement":"trans. Arthur W. Ryder, E. P. Dutton, 1912","year":1912},"basis":"pre-1930-us","sourceSha256":"8e415fe69e86f683c79f459dbc51b660971cf03da2d38343c43394acd67ea192","payloadChecksum":"5e714732ad7b9756cabe1bcf477b425bd8ef589f9e224b2ddf0907f259d6b306","chars":388055,"sections":44},
        load: () => import('./works/translations-of-shakuntala-and-other-works.js')
            .then(module => module.TRANSLATIONS_OF_SHAKUNTALA_AND_OTHER_WORKS_SECTIONS)
    },
    {
        meta: {"id":"the-little-clay-cart","title":"The Little Clay Cart","author":"Shudraka, traditional attribution","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Arthur W. Ryder, Harvard Oriental Series, 1905","year":1905},"basis":"pre-1930-us","sourceSha256":"eb4ce380df70889ac69def97c8306c1349ae6e1499f19964a823ae239642fe39","payloadChecksum":"c66a4d853654ba5cd2ac243aedb0d17e96dd34c2de8a9835f39ecb3941da6da8","chars":323123,"sections":31},
        load: () => import('./works/the-little-clay-cart.js')
            .then(module => module.THE_LITTLE_CLAY_CART_SECTIONS)
    },
    {
        meta: {"id":"twenty-two-goblins","title":"Twenty-Two Goblins","author":"traditional Sanskrit *Vetala* cycle; trans. Arthur W. Ryder","shelf":"eastern","traditionShelf":"eastern","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"University of Chicago Press, 1917","year":1917},"basis":"pre-1930-us","sourceSha256":"2b312b195c4ff331ed873d0cad6aed8e9d8c5bb8f76005a0a2d97d80f9111ed2","payloadChecksum":"b1ddd6d4aa43fc810cc1ebb7e3fd8d1ebad82f18c94c23901085accf1bc26241","chars":216177,"sections":7},
        load: () => import('./works/twenty-two-goblins.js')
            .then(module => module.TWENTY_TWO_GOBLINS_SECTIONS)
    },
    {
        meta: {"id":"strange-stories-from-a-chinese-studio","title":"Strange Stories from a Chinese Studio","author":"Pu Songling","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Herbert A. Giles, revised 2 vols., 1908","year":1908},"basis":"pre-1930-us","sourceSha256":"bd457257d3a4ee562a18547b3aa7457a1e6d4358a953da9c177d47288e90e8f3","payloadChecksum":"7cbd1481137f3541b3954ffc69d07355dac4a86eff7481ddba8aecf8d8308876","chars":1219764,"sections":59},
        load: () => import('./works/strange-stories-from-a-chinese-studio.js')
            .then(module => module.STRANGE_STORIES_FROM_A_CHINESE_STUDIO_SECTIONS)
    },
    {
        meta: {"id":"the-no-plays-of-japan","title":"The Nō Plays of Japan","author":"named and anonymous Noh dramatists; trans. Arthur Waley","shelf":"eastern","traditionShelf":"eastern","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"Alfred A. Knopf, New York, 1922","year":1922},"basis":"pre-1930-us","sourceSha256":"463f33a7b4fc1bb238878a870cce2273b11b4aa5484fbeeeb873d7d8170db6d1","payloadChecksum":"b9f8a9b5fd34a760b535d00e56e52e11452c00bf9495d25f7091312f5950e8cc","chars":321098,"sections":30},
        load: () => import('./works/the-no-plays-of-japan.js')
            .then(module => module.THE_NO_PLAYS_OF_JAPAN_SECTIONS)
    },
    {
        meta: {"id":"a-hundred-and-seventy-chinese-poems","title":"A Hundred and Seventy Chinese Poems","author":"named Chinese poets; trans. Arthur Waley","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"Alfred A. Knopf, New York, 1919 (London first ed. 1918)","year":1919},"basis":"pre-1930-us","sourceSha256":"9140e55f7e1523f6075d8464445a1dc49f17a4851d53bd89333883e08a0d390d","payloadChecksum":"0bb3318a6f89758f77fbcc2300905cbf36d86ede04c9d4fcfb06f4113358b4c2","chars":199118,"sections":22},
        load: () => import('./works/a-hundred-and-seventy-chinese-poems.js')
            .then(module => module.A_HUNDRED_AND_SEVENTY_CHINESE_POEMS_SECTIONS)
    },
    {
        meta: {"id":"the-shih-king-or-book-of-poetry","title":"The Shih King, or Book of Poetry","author":"anonymous early Chinese poets; trans. James Legge","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"classical","edition":{"statement":"*Sacred Books of the East*, vol. 3, Clarendon Press, 1879","year":1879},"basis":"author-death-70","sourceSha256":"29ae404c43edd4c107e13b7acb0e9a8dd44b8f9a80eaa0f3128052fd6eef9569","payloadChecksum":"ab67190fb098cc5366aa065d3f76c49a328c0e1da348a64f829479ed2bc45de2","chars":303372,"sections":29},
        load: () => import('./works/the-shih-king-or-book-of-poetry.js')
            .then(module => module.THE_SHIH_KING_OR_BOOK_OF_POETRY_SECTIONS)
    },
    {
        meta: {"id":"a-hundred-verses-from-old-japan","title":"A Hundred Verses from Old Japan","author":"the *Hyakunin Isshu* poets; trans. William N. Porter","shelf":"eastern","traditionShelf":"eastern","subjectShelves":["form"],"division":"imaginative","edition":{"statement":"Clarendon Press, 1909","year":1909},"basis":"author-death-70","sourceSha256":"25c08053de411cbb2ecac02ead8935c207990ec6867dabbab27464ad51522bf6","payloadChecksum":"e52b4e011392a33eee6af0e0ee134b6c8ff9f7d0af4e6b694b3904fccf1ce190","chars":111361,"sections":17},
        load: () => import('./works/a-hundred-verses-from-old-japan.js')
            .then(module => module.A_HUNDRED_VERSES_FROM_OLD_JAPAN_SECTIONS)
    },
    {
        meta: {"id":"kwaidan-stories-and-studies-of-strange-things","title":"Kwaidan: Stories and Studies of Strange Things","author":"Lafcadio Hearn","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"Houghton, Mifflin, Boston/New York, 1904","year":1904},"basis":"pre-1930-us","sourceSha256":"46f3fa0f2104f69b25331c256dc1b8280d610b5918389d4accf1641ada2b0fa0","payloadChecksum":"1229454b45182ae7d6d06dee8bdc14869e39625920ef5f477c1cd7aa535bf1c8","chars":210891,"sections":15},
        load: () => import('./works/kwaidan-stories-and-studies-of-strange-things.js')
            .then(module => module.KWAIDAN_STORIES_AND_STUDIES_OF_STRANGE_THINGS_SECTIONS)
    },
    {
        meta: {"id":"the-gulistan-or-rose-garden-of-sa-di","title":"The Gulistan; or, Rose Garden of Sa'di","author":"Sa'di","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. Edward Rehatsek, 1888","year":1888},"basis":"author-death-70","sourceSha256":"6e61d2862eb3eeca8136d239443edc7c9ab33fea608f04d9b333a0c337641ca3","payloadChecksum":"f1326a5015dda9f579d2c0e8fca43db278b8fffe461f1877ddc831474030f7c5","chars":244652,"sections":17},
        load: () => import('./works/the-gulistan-or-rose-garden-of-sa-di.js')
            .then(module => module.THE_GULISTAN_OR_ROSE_GARDEN_OF_SA_DI_SECTIONS)
    },
    {
        meta: {"id":"rubaiyat-of-omar-khayyam","title":"Rubáiyát of Omar Khayyám","author":"Omar Khayyam, attributed corpus; trans. Edward FitzGerald","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"FitzGerald's four principal editions, 1859–79, with variants","year":1859},"basis":"author-death-70","sourceSha256":"df3aa2528824ee0c39c9a3355e4622d81179395d3d79cbacc9dc3b39fa45e309","payloadChecksum":"7e5cc47d4c2096faffeb84e6095dc0e5664f22d4752eb4bfb0f60faede0bcfc0","chars":68111,"sections":4},
        load: () => import('./works/rubaiyat-of-omar-khayyam.js')
            .then(module => module.RUBAIYAT_OF_OMAR_KHAYYAM_SECTIONS)
    },
    {
        meta: {"id":"romance-of-the-three-kingdoms","title":"Romance of the Three Kingdoms","author":"Luo Guanzhong, traditional attribution","shelf":"eastern","traditionShelf":"eastern","subjectShelves":[],"division":"imaginative","edition":{"statement":"trans. C. H. Brewitt-Taylor, Kelly & Walsh, Shanghai, 2 vols., 1925; scan-backed Wikisource [vol. I](https://en.wikisource.org/wiki/File:Romance_of_the_Three_Kingdoms_-_tr._Brewitt-Taylor_-_Volume_1.djvu) and [vol. II](https://en.wikisource.org/wiki/File:Romance_of_the_Three_Kingdoms_-_tr._Brewitt-Taylor_-_Volume_2.djvu); `author-death-70`","year":1925},"basis":"author-death-70","sourceSha256":"7cff2d01cfc02c21232a8bb80f7a2cb17ca8a6a72f23174a9bbc28ed3cae6170","payloadChecksum":"666eed34b918c40887a9f7187102c035151c0bd6f08abbb4b8077a7fbf69b083","chars":3071801,"sections":126},
        load: () => import('./works/romance-of-the-three-kingdoms.js')
            .then(module => module.ROMANCE_OF_THE_THREE_KINGDOMS_SECTIONS)
    }
];
