// Generated by scripts/pin-kev-weights.mjs. Do not edit: run the script.
//
// For each device model: the ai-ecoverse/kev.js commit its bundle is fetched
// from, and the size and SHA-256 of every file the variant loads, the
// manifest first. A model missing here is refused before any fetch.
export default Object.freeze({});
