import { ATRIUM_CORPUS_VERSION, ATRIUM_SCHEMA_VERSION, freezeManifest } from './constants.js';
import {
  ATRIUM_PASSAGE_AUDITS,
  ATRIUM_SOURCE_AUDITS
} from './packs/pilot-v1/manifest.js';

const source = (
  id,
  domain,
  workTitle,
  author,
  provider,
  canonicalUrl,
  locatorScheme,
  language = 'en',
  originalLanguage = language
) => ({
  id,
  schemaVersion: ATRIUM_SCHEMA_VERSION,
  domain,
  kind: 'source-edition-candidate',
  workTitle,
  author,
  editor: null,
  translator: null,
  editionDate: null,
  language,
  originalLanguage,
  provider,
  canonicalUrl,
  canonicalId: null,
  locatorScheme,
  rights: {
    status: 'review-required',
    jurisdictions: [],
    license: null,
    attribution: null,
    reviewedAt: null
  },
  checksum: null,
  retrievedAt: null,
  status: 'draft'
});

const passage = (id, domain, sourceId, locator, label, editorialPurpose, perspectiveTags = []) => ({
  id,
  schemaVersion: ATRIUM_SCHEMA_VERSION,
  domain,
  kind: 'passage-candidate',
  sourceId,
  locator,
  canonicalLocator: null,
  label,
  editorialPurpose,
  estimatedWords: null,
  perspectiveTags,
  payloadPath: null,
  payloadChecksum: null,
  textVerified: false,
  rightsStatus: 'review-required',
  status: 'draft'
});

const sourceCandidates = [
  source('src-ogl-presocratic-fragments', 'philosophy', 'Presocratic fragment and testimonia collections', 'Multiple ancient authors', 'open-greek-latin', 'https://opengreekandlatin.org/', 'DK / Laks–Most concordance', 'grc', 'grc'),
  source('src-scaife-plato-theaetetus', 'philosophy', 'Theaetetus', 'Plato', 'scaife', 'https://scaife.perseus.org/', 'CTS', 'en', 'grc'),
  source('src-scaife-plato-apology', 'philosophy', 'Apology', 'Plato', 'scaife', 'https://scaife.perseus.org/', 'CTS', 'en', 'grc'),
  source('src-scaife-plato-meno', 'philosophy', 'Meno', 'Plato', 'scaife', 'https://scaife.perseus.org/', 'CTS', 'en', 'grc'),
  source('src-scaife-plato-republic', 'philosophy', 'Republic', 'Plato', 'scaife', 'https://scaife.perseus.org/', 'CTS', 'en', 'grc'),
  source('src-scaife-plato-phaedo', 'philosophy', 'Phaedo', 'Plato', 'scaife', 'https://scaife.perseus.org/', 'CTS', 'en', 'grc'),
  source('src-scaife-plato-timaeus', 'philosophy', 'Timaeus', 'Plato', 'scaife', 'https://scaife.perseus.org/', 'CTS', 'en', 'grc'),
  source('src-scaife-aristotle-metaphysics', 'philosophy', 'Metaphysics', 'Aristotle', 'scaife', 'https://scaife.perseus.org/', 'CTS / Bekker', 'en', 'grc'),
  source('src-scaife-aristotle-ethics', 'philosophy', 'Nicomachean Ethics', 'Aristotle', 'scaife', 'https://scaife.perseus.org/', 'CTS / Bekker', 'en', 'grc'),
  source('src-scaife-aristotle-de-anima', 'philosophy', 'De Anima', 'Aristotle', 'scaife', 'https://scaife.perseus.org/', 'CTS / Bekker', 'en', 'grc'),
  source('src-candidate-diogenes-laertius-x', 'philosophy', 'Lives of Eminent Philosophers, Book X', 'Diogenes Laertius', 'edition-audit', 'https://scaife.perseus.org/', 'book / section', 'en', 'grc'),
  source('src-candidate-epictetus-enchiridion', 'philosophy', 'Enchiridion', 'Epictetus', 'standard-ebooks-or-audited-pd', 'https://standardebooks.org/', 'section', 'en', 'grc'),
  source('src-candidate-seneca-letters', 'philosophy', 'Moral Letters to Lucilius', 'Seneca', 'audited-public-domain', 'https://www.gutenberg.org/', 'letter', 'en', 'lat'),
  source('src-candidate-marcus-meditations', 'philosophy', 'Meditations', 'Marcus Aurelius', 'standard-ebooks-or-audited-pd', 'https://standardebooks.org/', 'book / section', 'en', 'grc'),
  source('src-ogl-sextus-outlines', 'philosophy', 'Outlines of Pyrrhonism', 'Sextus Empiricus', 'open-greek-latin', 'https://opengreekandlatin.org/', 'book / section', 'en', 'grc'),
  source('src-perseus-cicero-academica', 'philosophy', 'Academica', 'Cicero', 'perseus', 'https://www.perseus.tufts.edu/', 'book / section', 'en', 'lat'),
  source('src-ogl-philo-creation', 'philosophy', 'On the Creation', 'Philo of Alexandria', 'open-greek-latin', 'https://opengreekandlatin.org/', 'section', 'en', 'grc'),
  source('src-ogl-plotinus-enneads', 'philosophy', 'Enneads', 'Plotinus', 'open-greek-latin', 'https://opengreekandlatin.org/', 'treatise / section', 'en', 'grc'),
  source('src-ogl-porphyry-life', 'philosophy', 'Life of Plotinus', 'Porphyry', 'open-greek-latin', 'https://opengreekandlatin.org/', 'section', 'en', 'grc'),
  source('src-ogl-porphyry-isagoge', 'philosophy', 'Isagoge', 'Porphyry', 'open-greek-latin', 'https://opengreekandlatin.org/', 'section', 'en', 'grc'),
  source('src-ogl-iamblichus-mysteries', 'philosophy', 'Reply to Porphyry / On the Mysteries', 'Iamblichus', 'open-greek-latin', 'https://opengreekandlatin.org/', 'book / section', 'en', 'grc'),
  source('src-ogl-proclus-elements', 'philosophy', 'Elements of Theology', 'Proclus', 'open-greek-latin', 'https://opengreekandlatin.org/', 'proposition', 'en', 'grc'),
  source('src-candidate-augustine-confessions', 'philosophy', 'Confessions', 'Augustine of Hippo', 'audited-public-domain', 'https://www.gutenberg.org/', 'book / chapter', 'en', 'lat'),
  source('src-candidate-dionysius-mystical', 'philosophy', 'Mystical Theology', 'Pseudo-Dionysius', 'audited-public-domain', 'https://www.gutenberg.org/', 'chapter', 'en', 'grc'),
  source('src-candidate-boethius-consolation', 'philosophy', 'Consolation of Philosophy', 'Boethius', 'standard-ebooks-or-audited-pd', 'https://standardebooks.org/', 'book / prose / meter', 'en', 'lat'),

  source('src-founders-boston-massacre-crown', 'history', 'Anonymous Summary of Crown Evidence: 24–25 October 1770', 'Unidentified trial reporter; witnesses Ebenezer Hinkley and Peter Cunningham', 'founders-online-primary-text-only', 'https://founders.archives.gov/documents/Adams/05-03-02-0001-0003-0004', 'case / evidentiary side / witness / trial date', 'en', 'en'),
  source('src-founders-boston-massacre-defense', 'history', 'Anonymous Summary of Defense Evidence: 25–27 October 1770', 'Unidentified trial reporter; witnesses Newton Prince and James Woodall', 'founders-online-primary-text-only', 'https://founders.archives.gov/documents/Adams/05-03-02-0001-0003-0006', 'case / evidentiary side / witness / trial date', 'en', 'en'),
  source('src-ukna-boston-tea-newspaper-1773', 'history', 'Massachusetts and Boston Weekly account of the destruction of the tea', 'Massachusetts and Boston Weekly newspaper', 'uk-national-archives-scan-and-transcript', 'https://www.nationalarchives.gov.uk/education/resources/boston-tea-party/boston-tea-party-source-4/', 'newspaper date / surviving extract / catalogue reference', 'en', 'en'),
  source('src-ukna-boston-tea-leslie-1773', 'history', 'Alexander Leslie to Viscount Barrington', 'Lieutenant Colonel Alexander Leslie', 'uk-national-archives-scan-and-transcript', 'https://www.nationalarchives.gov.uk/education/resources/boston-tea-party/boston-tea-party-source-3/', 'letter date / paragraph / catalogue reference', 'en', 'en'),
  source('src-bailly-maillard-october-days', 'history', 'Mémoires de Bailly, volume III: Déposition de Maillard sur les événements du 5 et du 6 octobre', 'Stanislas-Marie Maillard; published in the papers of Jean-Sylvain Bailly', 'internet-archive-scan-backed', 'https://archive.org/details/mmoiresdebailly03bail', 'volume / note / deposition / print page', 'fra', 'fra'),
  source('src-arcpa-womens-march-session', 'history', 'Archives parlementaires, night session of 5 October 1789', 'National Constituent Assembly; speakers recorded in the parliamentary archive', 'persee-archives-parlementaires-scan-backed', 'https://www.persee.fr/doc/arcpa_0000-0000_1877_num_9_1_5118_t1_0348_0000_24', 'series / volume / session / print page / incident', 'fra', 'fra'),

  source('src-candidate-rousseau-social-contract', 'history', 'The Social Contract', 'Jean-Jacques Rousseau', 'standard-ebooks-or-audited-pd', 'https://standardebooks.org/', 'book / chapter', 'en', 'fra'),
  source('src-avalon-vermont-constitution-1777', 'history', 'Constitution of Vermont', 'Vermont General Convention', 'yale-law-avalon', 'https://avalon.law.yale.edu/18th_century/vt01.asp', 'chapter / article / section', 'en', 'en'),
  source('src-nara-articles-confederation', 'history', 'Articles of Confederation', 'Continental Congress and the thirteen states', 'national-archives-original-and-transcript', 'https://www.archives.gov/milestone-documents/articles-of-confederation', 'article / engrossed original', 'en', 'en'),
  source('src-nara-bill-rights-1789', 'history', 'Joint Resolution Proposing Twelve Amendments to the Constitution', 'United States Congress', 'national-archives-original-and-transcript', 'https://www.archives.gov/milestone-documents/bill-of-rights', 'proposed article / engrossed original', 'en', 'en'),
  source('src-founders-franklin-examination', 'history', 'Examination before the Committee of the Whole of the House of Commons', 'Benjamin Franklin', 'founders-online', 'https://founders.archives.gov/documents/Franklin/01-13-02-0035', 'question / answer', 'en', 'en'),
  source('src-uk-patent-watt-913', 'history', 'A Method of Lessening the Consumption of Steam and Fuel in Fire Engines', 'James Watt', 'uk-patent-office-official-reprint-scan', 'https://commons.wikimedia.org/wiki/File:James_Watt_Patent_1769_No_913.pdf', 'principle / reprint page', 'en', 'en'),
  source('src-baines-cotton-manufacture-1835', 'history', 'History of the Cotton Manufacture in Great Britain', 'Edward Baines', 'internet-archive-scan-backed', 'https://archive.org/details/cottonmanufact00bain', 'chapter / print page / quoted patent element', 'en', 'en'),
  source('src-marsden-cotton-weaving-1895', 'history', 'Cotton Weaving: Its Development, Principles, and Practice', 'Richard Marsden', 'university-of-arizona-weaving-archive-scan', 'https://www2.cs.arizona.edu/patterns/weaving/books/mr_weave_1.pdf', 'chapter / print page / figure', 'en', 'en'),
  source('src-guardian-stockton-darlington-archive-1825', 'history', 'Stockton and Darlington Railway; Opening of the Stockton and Darlington Railway', 'Stockton and Darlington Railway Company; contemporary newspaper correspondent', 'guardian-digital-archive-historical-text', 'https://www.theguardian.com/uk-news/2025/sep/26/stockton-darlington-railway-first-public-passenger-service-opens-1825', 'document date / paragraph', 'en', 'en'),
  source('src-loc-lexington-depositions-1775', 'history', 'Massachusetts Provincial Congress letter and Lexington deposition', 'Massachusetts Provincial Congress; Elijah Saunderson', 'library-of-congress-scan-backed', 'https://www.loc.gov/item/05000059/', 'journal volume / print page / document / deposition', 'en', 'en'),
  source('src-uh-gage-dartmouth-1775', 'history', 'General Gage to the Earl of Dartmouth', 'Thomas Gage', 'university-of-houston-digital-history', 'https://www.digitalhistory.uh.edu/active_learning/explorations/revolution/account5_lexington.cfm', 'document date / paragraph', 'en', 'en'),
  source('src-founders-washington-orders-1775', 'history', 'General Orders, 4 July 1775', 'George Washington', 'founders-online-primary-text-only', 'https://founders.archives.gov/documents/Washington/03-01-02-0027', 'document date / order paragraph', 'en', 'en'),
  source('src-founders-franco-american-alliance-1778', 'history', 'The Franco-American Treaty of Alliance', 'France and the United States of America', 'founders-online-primary-text-only', 'https://founders.archives.gov/documents/Franklin/01-25-02-0476', 'article / signed bilingual instrument', 'en', 'en'),
  source('src-founders-yorktown-capitulation-1781', 'history', 'Articles of Capitulation between Washington and Cornwallis', 'George Washington, Charles Cornwallis, Jean-Baptiste de Rochambeau, Francois Joseph Paul de Grasse, and Thomas Symonds', 'founders-online-loc-collated', 'https://founders.archives.gov/documents/Washington/99-01-02-07199', 'article / manuscript image', 'en', 'en'),
  source('src-yale-treaty-paris-1763', 'history', 'Treaty of Paris 1763', 'Great Britain, France, Spain, and Portugal', 'yale-law-avalon', 'https://avalon.law.yale.edu/18th_century/paris763.asp', 'article', 'en', 'en'),
  source('src-nara-treaty-paris-1783', 'history', 'The Definitive Treaty of Peace 1783', 'Great Britain and the United States of America', 'national-archives-original-and-transcript', 'https://www.archives.gov/milestone-documents/treaty-of-paris', 'article / signed original', 'en', 'en'),
  source('src-uk-stamp-act-1765', 'history', 'Stamp Act 1765', 'Parliament of Great Britain', 'uk-legislation', 'https://www.legislation.gov.uk/', 'statute / clause', 'en', 'en'),
  source('src-loc-continental-congress-resolves', 'history', 'Declaration and Resolves of the First Continental Congress', 'Continental Congress', 'library-of-congress', 'https://www.loc.gov/item/05000059/', 'journal volume / page / resolution', 'en', 'en'),
  source('src-candidate-somerset-judgment', 'history', 'Somerset v Stewart judgment and reports', 'Court of King’s Bench', 'legal-edition-audit', 'https://www.oldbaileyonline.org/', 'report / page', 'en', 'en'),
  source('src-candidate-paine-common-sense', 'history', 'Common Sense', 'Thomas Paine', 'standard-ebooks-or-audited-pd', 'https://standardebooks.org/', 'section', 'en', 'en'),
  source('src-nara-us-declaration', 'history', 'Declaration of Independence', 'Continental Congress', 'nara', 'https://www.archives.gov/founding-docs/declaration', 'paragraph', 'en', 'en'),
  source('src-nara-us-constitution', 'history', 'Constitution of the United States', 'Constitutional Convention', 'nara', 'https://www.archives.gov/founding-docs/constitution', 'article / clause', 'en', 'en'),
  source('src-founders-federalist', 'history', 'The Federalist', 'Alexander Hamilton, James Madison, and John Jay', 'founders-online', 'https://founders.archives.gov/', 'essay / paragraph', 'en', 'en'),
  source('src-wikisource-sieyes-third-estate', 'history', 'Qu’est-ce que le tiers état ?', 'Emmanuel-Joseph Sieyès', 'wikisource-scan-backed', 'https://fr.wikisource.org/wiki/Qu%E2%80%99est-ce_que_le_tiers_%C3%A9tat_%3F', 'chapter / scan page', 'fra', 'fra'),
  source('src-wikisource-desmoulins-lanterne', 'history', 'Le Discours de la Lanterne aux Parisiens', 'Camille Desmoulins', 'wikisource-scan-backed', 'https://fr.wikisource.org/wiki/%C5%92uvres_de_Camille_Desmoulins/Tome_II/Le_Discours_de_la_Lanterne', 'work / paragraph / scan page', 'fra', 'fra'),
  source('src-frda-rights-man', 'history', 'Declaration of the Rights of Man and of the Citizen', 'National Constituent Assembly', 'frda', 'https://frda.stanford.edu/', 'article', 'fra', 'fra'),
  source('src-legifrance-constitution-year-viii', 'history', 'Constitution du 22 frimaire an VIII', 'French Republic', 'legifrance', 'https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000000571354', 'title / article / proclamation', 'fra', 'fra'),
  source('src-wikisource-code-civil-1804', 'history', 'Code civil des Français', 'French Republic', 'wikisource-scan-backed', 'https://fr.wikisource.org/wiki/Code_civil_des_Fran%C3%A7ais_1804/Texte_entier', 'book / title / article / scan page', 'fra', 'fra'),
  source('src-loc-anderson-napoleon-deposition', 'history', 'The Constitutions and Other Select Documents Illustrative of the History of France, 1789–1901', 'French Conservative Senate', 'library-of-congress', 'https://www.loc.gov/item/04025396/', 'document / date / print page', 'en', 'fra'),
  source('src-wienbibliothek-vienna-final-act', 'history', 'Acte du Congrès de Vienne du 9 Juin 1815, avec ses annexes', 'Congress of Vienna plenipotentiaries', 'wienbibliothek-official-scan', 'https://digital.wienbibliothek.at/wbrobv/content/titleinfo/2293309', 'preamble / article / print page', 'fra', 'fra'),
  source('src-elysee-republic-constitution-1793', 'history', 'Founding decrees of the Republic and Constitution of 24 June 1793', 'National Convention', 'elysee-primary-document', 'https://www.elysee.fr/la-presidence/la-constitution-du-24-juin-1793', 'decree / date / article', 'fra', 'fra'),
  source('src-gutenberg-robespierre-political-works', 'history', 'Discours par Maximilien Robespierre — 17 Avril 1792–27 Juillet 1794', 'Maximilien Robespierre', 'project-gutenberg-scan-backed', 'https://www.gutenberg.org/ebooks/29887', 'speech / date / paragraph', 'fra', 'fra'),
  source('src-moniteur-thermidor-convention', 'history', 'Réimpression de l’ancien Moniteur, volume XXI', 'Gazette nationale ou Le Moniteur universel; National Convention speakers', 'internet-archive-scan-backed', 'https://archive.org/details/reimpressiondela21unse', 'session / speaker / volume page', 'fra', 'fra'),
  source('src-gallica-rights-woman', 'history', 'Declaration of the Rights of Woman and of the Female Citizen', 'Olympe de Gouges', 'gallica', 'https://gallica.bnf.fr/', 'article', 'fra', 'fra'),
  source('src-candidate-equiano-narrative', 'history', 'The Interesting Narrative', 'Olaudah Equiano', 'standard-ebooks', 'https://standardebooks.org/', 'chapter / paragraph', 'en', 'en'),
  source('src-creole-patriote-insurgent-letter', 'history', 'Lettre originale des chefs des Nègres révoltés', 'Jean-François Papillon, Georges Biassou, and Charles Bélair', 'persee-scan-transcription-collation', 'https://www.persee.fr/doc/ahrf_0003-4436_1998_num_311_1_2095', 'letter / newspaper issue / scan page', 'fra', 'fra'),
  source('src-jcb-sonthonax-emancipation', 'history', 'Proclamation au nom de la République', 'Léger-Félicité Sonthonax', 'internet-archive-jcb-scan-backed', 'https://archive.org/details/proclamationauno00sont', 'broadside page / article', 'fra', 'fra'),
  source('src-moniteur-abolition-1794', 'history', 'Réimpression de l’ancien Moniteur, Convention nationale, 16 pluviôse an II', 'Gazette nationale ou Le Moniteur universel; National Convention speakers', 'internet-archive-scan-backed', 'https://archive.org/details/reimpressiondela19unse', 'session / speaker / volume page', 'fra', 'fra'),
  source('src-loc-haiti-constitutions', 'history', 'Les constitutions d’Haïti (1801–1885)', 'Multiple', 'library-of-congress', 'https://www.loc.gov/item/78396819/', 'document / article', 'fra', 'fra'),
  source('src-candidate-haiti-independence', 'history', 'Haitian Declaration of Independence', 'Jean-Jacques Dessalines and generals', 'institutional-edition-audit', 'https://www.loc.gov/', 'document / paragraph', 'fra', 'fra'),
  source('src-uk-slave-trade-act-1807', 'history', 'Slave Trade Act 1807', 'Parliament of the United Kingdom', 'uk-legislation', 'https://www.legislation.gov.uk/', 'statute / clause', 'en', 'en'),
  source('src-us-importation-act-1807', 'history', 'Act Prohibiting Importation of Slaves', 'United States Congress', 'library-of-congress', 'https://www.loc.gov/', 'statute / section', 'en', 'en'),
  source('src-bne-cadiz-constitution', 'history', 'Constitution of Cádiz', 'Cortes of Cádiz', 'bne', 'https://www.bne.es/', 'title / article', 'spa', 'spa'),
  source('src-candidate-venezuela-declaration', 'history', 'Venezuelan Declaration of Independence', 'Venezuelan Congress', 'institutional-edition-audit', 'https://library.brown.edu/create/modernlatinamerica/', 'paragraph', 'spa', 'spa'),
  source('src-candidate-jamaica-letter', 'history', 'Jamaica Letter', 'Simón Bolívar', 'original-language-edition-audit', 'https://library.brown.edu/create/modernlatinamerica/', 'paragraph', 'spa', 'spa'),
  source('src-candidate-angostura-address', 'history', 'Address to the Congress of Angostura', 'Simón Bolívar', 'original-language-edition-audit', 'https://library.brown.edu/create/modernlatinamerica/', 'paragraph', 'spa', 'spa'),
  source('src-loc-monroe-message', 'history', 'Seventh Annual Message to Congress', 'James Monroe', 'library-of-congress', 'https://www.loc.gov/', 'paragraph', 'en', 'en'),
  source('src-wikisource-ardouin-haiti-recognition-1825', 'history', 'Études sur l’histoire d’Haïti, tome 9', 'Beaubrun Ardouin; documents by Charles X and Jean-Pierre Boyer', 'wikisource-scan-backed-document-compilation', 'https://fr.wikisource.org/wiki/%C3%89tudes_sur_l%E2%80%99histoire_d%E2%80%99Ha%C3%AFti/Tome_9/4.7', 'chapter / document / scan page', 'fra', 'fra'),
  source('src-uk-slavery-abolition-act-1833', 'history', 'Slavery Abolition Act 1833', 'Parliament of the United Kingdom', 'uk-legislation', 'https://www.legislation.gov.uk/', 'statute / clause', 'en', 'en'),
  source('src-legifrance-french-abolition-1848', 'history', 'Decree abolishing slavery in the French colonies', 'French Provisional Government', 'legifrance', 'https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000295898', 'preamble / article', 'fra', 'fra'),
  source('src-candidate-communist-manifesto', 'history', 'Manifesto of the Communist Party', 'Karl Marx and Friedrich Engels', 'standard-ebooks-or-audited-pd', 'https://standardebooks.org/', 'chapter / paragraph', 'en', 'deu'),
  source('src-loc-seneca-declaration', 'history', 'Declaration of Sentiments', 'Seneca Falls Convention', 'library-of-congress', 'https://www.loc.gov/', 'resolution / paragraph', 'en', 'en'),
  source('src-argentina-tucuman-act-1816', 'history', 'Acta de la Independencia de las Provincias Unidas en Sud-América', 'Congress of Tucumán', 'argentina-government-transcript', 'https://www.argentina.gob.ar/sites/default/files/2025/07/acta_de_la_independencia_-_castellano.pdf', 'document / declaration / amendment', 'spa', 'spa'),
  source('src-agn-belgrano-pueyrredon-1816', 'history', 'Manuel Belgrano to Juan Martín de Pueyrredón', 'Manuel Belgrano', 'argentina-national-archive-document-scan', 'https://www.argentina.gob.ar/sites/default/files/monarquia_incaica_la_anarquia_y_otros_asuntos_militares_.pdf', 'archive reference / document date / paragraph', 'spa', 'spa'),
  source('src-argentina-tucuman-order-1816', 'history', 'Manifiesto del Congreso a los Pueblos', 'Congress of Tucumán', 'argentina-national-museum-object-and-transcript-collation', 'https://www.argentina.gob.ar/node/506237', 'document / decree / date', 'spa', 'spa'),
  source('src-mexico-plan-iguala-1821', 'history', 'Plan de Iguala', 'Agustín de Iturbide', 'mexico-chamber-inehrm-transcript', 'https://www.diputados.gob.mx/Asesor-Legislativo/docs/7.Constituciones/Documentos/h.pdf', 'preamble / numbered base / date', 'spa', 'spa'),
  source('src-inehrm-mexico-independence-act-1821', 'history', 'Acta de Independencia del Imperio Mexicano', 'Supreme Provisional Governing Junta of the Mexican Empire', 'inehrm-official-transcript', 'https://inehrm.gob.mx/work/models/Constitucion1917/Resource/263/1/images/Independencia19_2.pdf', 'document / paragraph / signature block', 'spa', 'spa'),
  source('src-peru-bicentennial-independence-act-1821', 'history', 'Acta de declaración de la independencia del Perú', 'Cabildo of Lima', 'peru-bicentennial-institutional-transcript', 'https://bicentenario.gob.pe/15-julio-1821-firma-acta-independencia-peru/', 'municipal book / act / date', 'spa', 'spa'),
  source('src-peru-congress-protector-decree-1821', 'history', 'Decreto asumiendo el mando supremo político y militar con el título de Protector', 'José de San Martín', 'peru-congress-official-transcript', 'https://www.congreso.gob.pe/Docs/participacion/museo/congreso/files/mensajes/1822-1840/a-mensaje-1821-3.pdf', 'document / paragraph / numbered article', 'spa', 'spa'),
  source('src-bndigital-brazil-manifesto-peoples-1822', 'history', 'Manifesto do Príncipe Regente aos Povos do Brasil', 'Pedro, Prince Regent; drafted by Joaquim Gonçalves Ledo', 'brazil-national-library-newspaper-scan', 'https://objdigital.bn.br/acervo_digital/div_periodicos/gazeta_rj/gazeta_rj_1822/gazeta_rj_1822_094_suplemento.pdf', 'newspaper issue / print page / paragraph', 'por', 'por'),
  source('src-brazil-chamber-council-session-1822', 'history', 'Ata da sessão nº 13 do Conselho de Estado', 'Council of State; Joaquim Gonçalves Ledo, secretary', 'brazil-chamber-archival-exhibition-transcript', 'https://www2.camara.leg.br/a-camara/visiteacamara/cultura-na-camara/arquivos/dois-de-julho-2014-a-independencia-do-brasil-na-bahia', 'session / date / archival extract', 'por', 'por'),
  source('src-cachoeira-adhesion-letter-1822', 'history', 'Câmara de Cachoeira ao Príncipe Regente', 'Municipal chamber of Cachoeira', 'ufba-scan-backed-document-quotation', 'https://ppgh.ufba.br/sites/ppgh.ufba.br/files/13_entre_adesoes_e_rupturas_projetos_e_identidades_politicas_na_bahia_1808-1824.pdf', 'letter date / quoted document / print edition reference', 'por', 'por'),
  source('src-hansard-apprenticeship-debate-1838', 'history', 'Abolition of Negro Apprenticeship', 'House of Commons; Sir George Strickland and Sir George Grey', 'uk-parliament-historic-hansard', 'https://api.parliament.uk/historic-hansard/commons/1838/mar/29/abolition-of-negro-apprenticesship', 'chamber / date / volume / column / speaker / paragraph', 'en', 'en'),
  source('src-unb-barbados-apprenticeship-termination-1838', 'history', 'An Act for terminating the Apprenticeship of the Praedial Labourers within this Island', 'Barbados Legislature; Colonial Office abstract', 'unb-laws-enslavement-freedom-transcript', 'https://slaveryandfreedomlaws.lib.unb.ca/laws/barbados-1838', 'archive series / volume / page / clause abstract', 'en', 'en')
];

const passageCandidates = [
  passage('pass-boston-massacre-crown-evidence', 'history', 'src-founders-boston-massacre-crown', '24–25 October 1770; Hinkley and Cunningham testimony', 'Crown witnesses reconstruct the firing', 'Two prosecution-side witnesses disagree in detail while locating sticks, snow, bayonets, loading, and the absence of a heard order to fire.', ['testimony', 'trial-record', 'massachusetts', 'crowd', 'contested-evidence']),
  passage('pass-boston-massacre-defense-evidence', 'history', 'src-founders-boston-massacre-defense', '25–27 October 1770; Prince and Woodall testimony', 'Defense witnesses contest command and crowd conduct', 'Newton Prince and James Woodall describe threats, blows, thrown objects, and a possible civilian command while denying that Preston ordered the firing.', ['testimony', 'trial-record', 'massachusetts', 'counteraccount', 'black-witness']),
  passage('pass-boston-tea-colonial-newspaper-1773', 'history', 'src-ukna-boston-tea-newspaper-1773', '23 December 1773, complete surviving extract, CO 5/91', 'Destruction staged as disciplined public action', 'A colonial newspaper narrates disguise, spectatorship, destruction, protected property, civic quiet, and popular joy as evidence of purposeful collective discipline.', ['newspaper', 'massachusetts', 'crowd', 'publicity', 'partisan-account']),
  passage('pass-boston-tea-leslie-letter-1773', 'history', 'src-ukna-boston-tea-leslie-1773', '17 December 1773, complete letter, WO 40/1', 'A military observer reports who rules Boston', 'Leslie converts the same event into military readiness, governmental restraint, threatened officials, and a judgment that the crowd now rules the town.', ['military-letter', 'british', 'counteraccount', 'crowd', 'intelligence']),
  passage('pass-maillard-womens-march-deposition', 'history', 'src-bailly-maillard-october-days', 'Maillard deposition, print pages 407–408, selected continuous paragraphs', 'The marchers admitted through a mediator', 'Maillard records women excluding men, authorizing his entry, condemning municipal papers, demanding bread, and asserting greater resolve, while casting himself as the agent who contained their action.', ['deposition', 'france', 'crowd', 'mediated-voice', 'self-exculpatory']),
  passage('pass-assembly-womens-march-1789', 'history', 'src-arcpa-womens-march-session', 'night session of 5 October 1789, page 348, complete incident', 'Bread enters the Assembly, then the hall is cleared', 'The parliamentary record preserves the women’s demand that grain outrank criminal procedure, then shifts immediately to institutional dignity, disorder, and evacuation.', ['parliamentary-record', 'france', 'crowd', 'institutional-mediation', 'bread']),
  passage('pass-anaximander-fragment', 'philosophy', 'src-ogl-presocratic-fragments', 'DK 12 B1 / Laks–Most equivalent', 'Anaximander on origin and return', 'Origin, order, and return.', ['fragmentary', 'early-greek']),
  passage('pass-heraclitus-logos', 'philosophy', 'src-ogl-presocratic-fragments', 'selected Logos fragments; DK/current concordance', 'Heraclitus on logos', 'Logos and common order.', ['fragmentary', 'early-greek']),
  passage('pass-parmenides-being', 'philosophy', 'src-ogl-presocratic-fragments', 'fragment B8, selected lines', 'Parmenides on being', 'Being and the limits of coming-to-be.', ['fragmentary', 'early-greek']),
  passage('pass-empedocles-roots', 'philosophy', 'src-ogl-presocratic-fragments', 'selected fragments on roots, Love, and Strife', 'Empedocles on roots and forces', 'A pluralist response to Eleatic argument.', ['fragmentary', 'early-greek']),
  passage('pass-democritus-atoms', 'philosophy', 'src-ogl-presocratic-fragments', 'Burnet §§173–175; Aristotle and Theophrastus testimonia', 'Leucippus and Democritus on atoms and void', 'Atoms, void, and the Eleatic problem of motion.', ['fragmentary', 'early-greek']),
  passage('pass-protagoras-measure', 'philosophy', 'src-scaife-plato-theaetetus', '151e–160e, selected', 'Protagoras through Plato’s witness', 'Relativism through a critical witness.', ['critical-witness', 'classical']),
  passage('pass-socrates-apology', 'philosophy', 'src-scaife-plato-apology', '20c–23b and 28e–30b', 'Wisdom and the examined life', 'Socratic wisdom, examination, and obligation.', ['dramatic-dialogue', 'classical']),
  passage('pass-plato-recollection', 'philosophy', 'src-scaife-plato-meno', '80d–86c, selected', 'Inquiry and recollection', 'The paradox of inquiry and a proposed response.', ['dramatic-dialogue', 'classical']),
  passage('pass-plato-divided-line', 'philosophy', 'src-scaife-plato-republic', 'VI 507b–511e', 'The divided line', 'Knowledge and intelligibility.', ['classical', 'epistemology']),
  passage('pass-plato-cave', 'philosophy', 'src-scaife-plato-republic', 'VII 514a–521b, selected', 'The cave and the return', 'Education, transformation, and return.', ['classical', 'education']),
  passage('pass-plato-forms', 'philosophy', 'src-scaife-plato-phaedo', '74a–76e', 'Equality, recollection, and Forms', 'A route from equal things to equality itself.', ['classical', 'metaphysics']),
  passage('pass-plato-cosmos', 'philosophy', 'src-scaife-plato-timaeus', '27d–29d', 'Model, becoming, and likely account', 'The epistemic posture of cosmological explanation.', ['classical', 'cosmology']),
  passage('pass-aristotle-first-causes', 'philosophy', 'src-scaife-aristotle-metaphysics', 'I.3, 983a24–984b22, selected', 'Aristotle’s predecessors', 'A retrospective genealogy of first causes.', ['classical', 'historiography']),
  passage('pass-aristotle-substance', 'philosophy', 'src-scaife-aristotle-metaphysics', 'VII.1–3, selected', 'Being and substance', 'Aristotle’s architecture of substance.', ['classical', 'metaphysics']),
  passage('pass-aristotle-human-good', 'philosophy', 'src-scaife-aristotle-ethics', 'I.7, 1097b22–1098a20', 'The human good', 'Function, activity, and flourishing.', ['classical', 'ethics']),
  passage('pass-aristotle-soul', 'philosophy', 'src-scaife-aristotle-de-anima', 'II.1, 412a3–413a10', 'Soul as actuality', 'Form, body, and living actuality.', ['classical', 'psychology']),
  passage('pass-epicurus-gods-death', 'philosophy', 'src-candidate-diogenes-laertius-x', 'Letter to Menoeceus 122–135, selected', 'Gods, death, desire, and pleasure', 'Release from fear and the ordering of desire.', ['hellenistic', 'ethics']),
  passage('pass-epicurus-doctrines', 'philosophy', 'src-candidate-diogenes-laertius-x', 'Principal Doctrines 1–5 and 27–28', 'Freedom from fear and friendship', 'Compact propositions on tranquility and friendship.', ['hellenistic', 'ethics']),
  passage('pass-epictetus-control', 'philosophy', 'src-candidate-epictetus-enchiridion', '1', 'What is up to us', 'The opening distinction structuring Stoic practice.', ['roman-stoic', 'practice']),
  passage('pass-seneca-inner-spirit', 'philosophy', 'src-candidate-seneca-letters', 'Letter 41', 'The inward source of dignity', 'Divinity, reason, and inward dignity.', ['roman-stoic', 'practice']),
  passage('pass-marcus-morning', 'philosophy', 'src-candidate-marcus-meditations', 'II.1–5', 'The morning meditation', 'Social nature, difficult encounters, and deliberate action.', ['roman-stoic', 'practice']),
  passage('pass-sextus-skeptical-way', 'philosophy', 'src-ogl-sextus-outlines', 'I.1–12', 'The skeptical way', 'Inquiry, equipollence, and suspension.', ['hellenistic', 'skepticism']),
  passage('pass-cicero-academic', 'philosophy', 'src-perseus-cicero-academica', 'II, selected', 'Academic arguments about apprehension', 'A distinct skeptical tradition preserved in Latin.', ['roman', 'skepticism']),
  passage('pass-philo-creation', 'philosophy', 'src-ogl-philo-creation', 'selected sections', 'Creation and intelligible model', 'Scriptural exegesis in a Platonist vocabulary.', ['imperial', 'jewish-philosophy']),
  passage('pass-plotinus-beauty', 'philosophy', 'src-ogl-plotinus-enneads', 'I.6, selected', 'Beauty and ascent', 'Beauty as a route toward intelligible reality.', ['late-antique', 'platonism']),
  passage('pass-plotinus-hypostases', 'philosophy', 'src-ogl-plotinus-enneads', 'V.1, selected', 'The primary hypostases', 'The One, Intellect, and Soul.', ['late-antique', 'platonism']),
  passage('pass-porphyry-life-14', 'philosophy', 'src-ogl-porphyry-life', '14', 'Plotinus’s sources and teaching', 'Biographical testimony about a philosophical practice.', ['late-antique', 'testimony']),
  passage('pass-porphyry-isagoge', 'philosophy', 'src-ogl-porphyry-isagoge', 'I and II, opening definition of genus, selected', 'Genera and species', 'Logical questions that shape later transmission.', ['late-antique', 'logic']),
  passage('pass-iamblichus-theurgy', 'philosophy', 'src-ogl-iamblichus-mysteries', 'I.11 opening and I.12', 'Reason, ritual, and divine action', 'A defense of theurgy against Porphyrian criticism.', ['late-antique', 'theurgy']),
  passage('pass-proclus-propositions', 'philosophy', 'src-ogl-proclus-elements', 'propositions 1–4', 'Unity and multiplicity', 'A proposition-based architecture of procession.', ['late-antique', 'system']),
  passage('pass-augustine-platonic-books', 'philosophy', 'src-candidate-augustine-confessions', 'VII.9–21, selected', 'The books of the Platonists', 'Augustine’s account of appropriation and difference.', ['christian', 'transmission']),
  passage('pass-augustine-time', 'philosophy', 'src-candidate-augustine-confessions', 'XI.14–28, selected', 'Time, memory, and attention', 'An inward analysis of temporal experience.', ['christian', 'time']),
  passage('pass-dionysius-mystical', 'philosophy', 'src-candidate-dionysius-mystical', 'I', 'Apophatic ascent', 'The movement beyond affirmation and negation.', ['christian', 'apophasis']),
  passage('pass-boethius-eternity', 'philosophy', 'src-candidate-boethius-consolation', 'V, selected', 'Providence, eternity, and freedom', 'A Latin meditation on foreknowledge and freedom.', ['latin', 'transmission']),

    passage('pass-rousseau-association', 'history', 'src-candidate-rousseau-social-contract', 'Book I, Chapter VI, selected', 'The act of association', 'Popular sovereignty and legitimate association.', ['political-theory', 'europe']),
    passage('pass-vermont-constitution-1777', 'history', 'src-avalon-vermont-constitution-1777', 'Chapter I, Articles I, III, VI, and VIII; Chapter II, Section VI', 'Freedom with qualifications', 'Natural rights, constrained servitude, religious language, popular accountability, and the legal boundary of freemanship.', ['constitution', 'rights', 'slavery', 'suffrage', 'vermont']),
  passage('pass-articles-confederation-1777', 'history', 'src-nara-articles-confederation', 'Articles I–V, selected complete clauses', 'A league of sovereign states', 'State sovereignty, mutual defence, interstate privileges, and equal state voting within confederation.', ['constitution', 'confederation', 'federalism', 'united-states']),
  passage('pass-us-bill-rights-proposal-1789', 'history', 'src-nara-bill-rights-1789', 'preamble and proposed Articles I–XII', 'Twelve proposed, ten ratified', 'The enrolled proposal preserves the two amendments that did not enter the 1791 Bill of Rights alongside the ten that did.', ['constitution', 'amendment', 'rights', 'ratification', 'united-states']),
  passage('pass-franklin-war-finance-1766', 'history', 'src-founders-franklin-examination', 'questions 2–4, 14–16, and 27–28, selected', 'Who paid for the last war?', 'Franklin’s parliamentary testimony contests the metropolitan burden narrative through provincial taxes, debt, troop contributions, and specie scarcity.', ['testimony', 'british-atlantic', 'fiscal-state', 'colonial-perspective']),
  passage('pass-watt-steam-principles-1769', 'history', 'src-uk-patent-watt-913', 'selected principles I–IV, VI–VII; 1855 reprint pages 2–3', 'Heat, condensation, and a patent boundary', 'Watt’s own specification defines an interdependent economy of heat, condensation, air removal, expansion, and sealing rather than a one-device invention story.', ['patent', 'steam', 'energy', 'technical-record', 'britain']),
  passage('pass-arkwright-water-frame-system-1769', 'history', 'src-baines-cotton-manufacture-1835', 'Chapter IX, print pages 147, 151–154, selected complete paragraphs and patent extract', 'Rollers, drive, and the factory as machine', 'A contemporary technical history distinguishes earlier roller spinning from Arkwright’s combination of mechanism, power, scale, and factory organization.', ['patent', 'textiles', 'factory-system', 'technical-history', 'britain']),
  passage('pass-cartwright-power-loom-iteration-1785', 'history', 'src-marsden-cotton-weaving-1895', 'Chapter III, print pages 61–63, selected', 'A crude first loom becomes an engineering program', 'The first specification, its operational failure, and the second design make iteration—not a finished 1785 machine—the historical unit.', ['patent', 'textiles', 'iteration', 'technical-history', 'britain']),
  passage('pass-stockton-darlington-opening-1825', 'history', 'src-guardian-stockton-darlington-archive-1825', 'company notice of 24 September and opening report of 15 October 1825, selected complete paragraphs', 'A railway as a mixed transport system', 'The opening record joins corporate notice, gradients, fixed engines, rope haulage, locomotive power, horses, freight, passengers, and public spectacle.', ['company-record', 'newspaper-report', 'railway', 'infrastructure', 'britain']),
  passage('pass-lexington-provincial-evidence-1775', 'history', 'src-loc-lexington-depositions-1775', 'Journals of the Continental Congress, volume II, print pages 26–29; 26 April letter and Saunderson deposition, selected', 'Evidence sent across the Atlantic', 'A provincial letter discloses the political circulation of its evidence packet before one sworn account states who fired first at Lexington.', ['state-record', 'testimony', 'war', 'public-opinion']),
  passage('pass-gage-lexington-report-1775', 'history', 'src-uh-gage-dartmouth-1775', '22 April 1775 report, complete substantive paragraphs', 'Gage reports the opening conflict', 'The British commander describes an arms-seizure expedition, assigns the first fire to provincial opponents, and confronts mass mobilization around Boston.', ['military-report', 'british', 'war', 'counteraccount']),
  passage('pass-washington-continental-orders-1775', 'history', 'src-founders-washington-orders-1775', '4 July 1775 general orders, selected complete orders', 'From colonial forces to a Continental army', 'Stores, Continental command, discipline, sanitation, smallpox control, and intelligence reveal the organizational work behind an army.', ['military-order', 'administration', 'logistics', 'continental-army']),
  passage('pass-franco-american-alliance-1778', 'history', 'src-founders-franco-american-alliance-1778', 'preamble and Articles 1–3, 8, and 11, English signed text', 'Alliance makes independence a common war aim', 'Mutual effort, guarantees, and the prohibition on a separate peace internationalize the American war and bind military action to recognized independence.', ['treaty', 'diplomacy', 'alliance', 'war']),
  passage('pass-yorktown-capitulation-1781', 'history', 'src-founders-yorktown-capitulation-1781', 'preamble and Articles 1–4, 8, 10, 13, and 14, selected', 'Combined victory administered as surrender', 'The capitulation identifies French and American command, allocates prisoners and naval captures, and negotiates property, loyalists, communications, and interpretation.', ['military-agreement', 'franco-american', 'surrender', 'war']),
  passage('pass-treaty-paris-1763', 'history', 'src-yale-treaty-paris-1763', 'Articles IV, X, and XI, selected', 'A global peace apportions empire', 'The treaty converts global war into territorial, commercial, religious, and military settlements across several imperial theatres.', ['treaty', 'global', 'war-empire', 'diplomacy']),
  passage('pass-treaty-paris-1783', 'history', 'src-nara-treaty-paris-1783', 'Articles I, IV, and VI–VIII', 'Recognition and the obligations of peace', 'Recognition, debt, amnesty, military withdrawal, property, archives, and navigation define who enters the settlement and what survives the war.', ['treaty', 'atlantic', 'recognition', 'diplomacy', 'slavery']),
  passage('pass-stamp-act', 'history', 'src-uk-stamp-act-1765', 'selected operative clauses', 'Imperial taxation in statute', 'The legal machinery behind an Atlantic constitutional crisis.', ['state-record', 'british-atlantic']),
  passage('pass-first-continental-resolves-1774', 'history', 'src-loc-continental-congress-resolves', '14 October 1774, opening grievance and Resolves 1, 4, and 9, selected', 'Rights within the empire', 'The Congress connects postwar revenue and coercive administration to a coordinated claim of consent and colonial legislative authority.', ['congressional-record', 'british-atlantic', 'resistance', 'constitutional-claim']),
  passage('pass-somerset', 'history', 'src-candidate-somerset-judgment', 'selected judgment or authenticated report', 'Law, slavery, and jurisdiction', 'The reach and limits of the Somerset judgment.', ['legal-record', 'slavery']),
  passage('pass-common-sense', 'history', 'src-candidate-paine-common-sense', 'introduction and selected monarchy/republic sections', 'The case for independence', 'A widely circulated argument for political separation.', ['print', 'revolutionary']),
  passage('pass-us-declaration', 'history', 'src-nara-us-declaration', 'grievances and conclusion', 'Declaration and universal claim', 'Independence, grievance, and political universality.', ['state-record', 'united-states']),
  passage('pass-us-constitution', 'history', 'src-nara-us-constitution', 'Preamble and selected structural clauses', 'Federal design', 'A constitutional architecture read with its exclusions.', ['state-record', 'united-states']),
  passage('pass-federalist-10', 'history', 'src-founders-federalist', 'No. 10, selected', 'Faction and the extended republic', 'An argument for constitutional scale and representation.', ['political-print', 'united-states']),
  passage('pass-sieyes-third-estate', 'history', 'src-wikisource-sieyes-third-estate', 'opening plan and Chapter I through the public functions', 'The Third Estate as the political nation', 'A pre-assembly argument that labor, public function, and the nation reside in the Third Estate.', ['political-print', 'france', 'assembly']),
  passage('pass-desmoulins-lanterne', 'history', 'src-wikisource-desmoulins-lanterne', 'passage beginning “Tu as cru…” through the Charles IX question', 'The Bastille and popular justice', 'A non-state revolutionary voice celebrating rupture while confronting summary justice and conspiracy.', ['political-print', 'france', 'popular-voice']),
  passage('pass-rights-man', 'history', 'src-frda-rights-man', 'selected articles', 'Rights and sovereignty', 'A revolutionary declaration of rights and political authority.', ['state-record', 'france']),
  passage('pass-constitution-year-viii', 'history', 'src-legifrance-constitution-year-viii', 'Articles 25, 28, 34, 41–42, and Consuls’ proclamation, selected', 'Representative forms and consular power', 'The constitutional settlement preserves representative institutions in form while giving legislative initiative, appointments, and final executive decision to the First Consul.', ['state-record', 'france', 'consulate', 'executive-power']),
  passage('pass-code-civil-1804', 'history', 'src-wikisource-code-civil-1804', 'Articles 2, 7–8, 212–217, 371–374, 544–545, and 1134–1135', 'Civil equality, property, and household authority', 'The code stabilizes civil rights, property, and contract while making marital and paternal hierarchy part of the same legal settlement.', ['legal-record', 'france', 'civil-law', 'family', 'property']),
  passage('pass-senate-deposition-napoleon-1814', 'history', 'src-loc-anderson-napoleon-deposition', '3–4 April 1814 decree, selected; Anderson pages 444–446', 'The Senate indicts the imperial regime', 'A Senate that had sustained the empire recasts taxation, legislative suppression, war, and concentrated power as grounds for deposition amid allied occupation.', ['state-record', 'france', 'war-empire', 'partisan-institutional-voice']),
  passage('pass-congress-vienna-final-act-1815', 'history', 'src-wienbibliothek-vienna-final-act', 'preamble and Articles I, CVIII–CIX, selected', 'Territory, representation, and navigation after war', 'The settlement joins dynastic territorial allocation and discretionary representation to multilateral rules for navigation and commerce.', ['treaty', 'europe', 'diplomacy', 'settlement']),
  passage('pass-republic-constitution-1793', 'history', 'src-elysee-republic-constitution-1793', 'decrees of 21–25 September 1792; 1793 Declaration preamble and Articles 1–4, 9, 25, 28–29, 31, 33–35', 'Republic and popular sovereignty', 'The abolition of monarchy and the constitutional promises made in the name of an indivisible republic.', ['state-record', 'france', 'republic']),
  passage('pass-robespierre-virtue-terror', 'history', 'src-gutenberg-robespierre-political-works', '18 pluviôse an II (5 February 1794), selected', 'Virtue and terror', 'Robespierre’s argument joining revolutionary government, virtue, terror, and national self-preservation.', ['parliamentary-speech', 'france', 'terror']),
  passage('pass-thermidor-convention', 'history', 'src-moniteur-thermidor-convention', '9 thermidor an II (27 July 1794), volume XXI, pages 335–336', 'The Convention turns on Robespierre', 'The contested voices, interruptions, accusation, and arrest decree of 9 Thermidor.', ['parliamentary-record', 'france', 'thermidor']),
  passage('pass-rights-woman', 'history', 'src-gallica-rights-woman', 'selected articles', 'Counterclaim and exclusion', 'A gendered counterclaim written in the declaration form.', ['countervoice', 'france']),
  passage('pass-equiano', 'history', 'src-candidate-equiano-narrative', 'selected authenticated episode', 'Enslavement, commerce, and testimony', 'First-person testimony within abolitionist print culture.', ['counterarchive', 'atlantic']),
  passage('pass-haiti-insurgent-letter-1792', 'history', 'src-creole-patriote-insurgent-letter', 'July 1792 letter, selected; transcription pages 133–135', 'General liberty or death', 'Insurgent leaders claim natural equality, general emancipation, amnesty, negotiated peace, and paid labor.', ['counterarchive', 'haiti', 'insurgent-letter']),
  passage('pass-sonthonax-emancipation-1793', 'history', 'src-jcb-sonthonax-emancipation', '29 August 1793 broadside, preamble and Articles II, IX, XI, XII, XXVII, and XXXIII', 'Freedom and the plantation regime', 'Colonial emancipation grants citizenship and wages while binding cultivators to plantations and disciplinary law.', ['state-record', 'haiti', 'emancipation', 'labor']),
  passage('pass-convention-abolition-1794', 'history', 'src-moniteur-abolition-1794', '16 pluviôse an II proceedings, debate and decree, selected', 'Abolition debated and decreed', 'The Convention generalizes colonial abolition and immediately confronts the problem of implementation.', ['parliamentary-record', 'france', 'haiti', 'emancipation']),
  passage('pass-haiti-constitution-1801', 'history', 'src-loc-haiti-constitutions', 'selected articles on freedom, territory, labor, and authority', 'Freedom and constitutional power', 'Emancipation alongside centralized labor and executive power.', ['state-record', 'haiti']),
  passage('pass-haiti-independence-1804', 'history', 'src-candidate-haiti-independence', 'selected paragraphs', 'Independence after slavery and war', 'A declaration following revolutionary emancipation and anticolonial war.', ['state-record', 'haiti']),
  passage('pass-haiti-recognition-1825', 'history', 'src-wikisource-ardouin-haiti-recognition-1825', 'Charles X ordinance, preamble and Articles 1–3; Boyer proclamation, selected complete paragraphs', 'Recognition under tariff and indemnity conditions', 'Paired French and Haitian documents distinguish independence achieved in 1804 from formal recognition in 1825 while exposing the commercial and indemnity conditions attached to recognition.', ['state-record', 'haiti', 'france', 'recognition', 'sovereignty', 'debt']),
  passage('pass-uk-slave-trade-act', 'history', 'src-uk-slave-trade-act-1807', 'selected operative clauses', 'Trade prohibition and enforcement', 'Prohibition of the trade without abolition of colonial slavery.', ['legal-record', 'british-empire']),
  passage('pass-us-importation-act', 'history', 'src-us-importation-act-1807', 'selected sections', 'Importation prohibited, slavery retained', 'A trade prohibition distinguished from emancipation.', ['legal-record', 'united-states']),
  passage('pass-cadiz', 'history', 'src-bne-cadiz-constitution', 'selected articles on nation, sovereignty, and citizenship', 'Imperial constitutionalism', 'Constitutional nationhood across an empire in crisis.', ['state-record', 'spanish-atlantic']),
  passage('pass-venezuela-declaration', 'history', 'src-candidate-venezuela-declaration', 'selected paragraphs', 'Spanish American independence', 'A declaration of sovereignty amid war and social conflict.', ['state-record', 'venezuela']),
  passage('pass-jamaica-letter', 'history', 'src-candidate-jamaica-letter', 'selected original Spanish paragraphs', 'Continental diagnosis and political futures', 'Bolívar’s analysis of colonial inheritance and possible futures.', ['political-letter', 'spanish-america']),
  passage('pass-angostura', 'history', 'src-candidate-angostura-address', 'selected original Spanish paragraphs', 'Republican design and executive power', 'A constitutional address shaped by regional history and strong executive preference.', ['political-speech', 'spanish-america']),
  passage('pass-monroe-message', 'history', 'src-loc-monroe-message', 'relevant paragraphs', 'Hemispheric policy', 'A United States claim about European intervention and the Americas.', ['state-record', 'united-states']),
  passage('pass-slavery-abolition-1833', 'history', 'src-uk-slavery-abolition-act-1833', 'selected clauses', 'Emancipation, apprenticeship, and compensation', 'Abolition legislation read through its delays and beneficiaries.', ['legal-record', 'british-empire']),
  passage('pass-french-abolition-1848', 'history', 'src-legifrance-french-abolition-1848', 'preamble and Articles 1–9', 'Colonial re-abolition', 'The 1848 decree distinguished from 1794 and Napoleon’s reversal.', ['state-record', 'french-empire']),
  passage('pass-communist-manifesto', 'history', 'src-candidate-communist-manifesto', 'I, selected', 'Class and industrial transformation', 'An interpretation of industrial capitalism and class conflict.', ['political-print', 'europe']),
  passage('pass-seneca-declaration', 'history', 'src-loc-seneca-declaration', 'selected resolutions and declaration paragraphs', 'Rights claim in an inherited form', 'Women’s equality argued through the language of revolutionary declaration.', ['social-movement', 'united-states']),
  passage('pass-tucuman-independence-act-1816', 'history', 'src-argentina-tucuman-act-1816', '9 July act with 19 July foreign-domination amendment', 'Congress declares, but does not finish constituting, a nation', 'The act claims unanimous independence for represented provinces while leaving their political form to justice and circumstance.', ['state-record', 'argentina', 'congress', 'independence', 'territorial-uncertainty']),
  passage('pass-belgrano-government-unsettled-1816', 'history', 'src-agn-belgrano-pueyrredon-1816', '12 July 1816 letter, selected continuous substantive paragraphs', 'Independence without a settled government', 'Three days after the act, Belgrano asks what form will sustain independence, advances an Inca constitutional monarchy, and exposes unresolved authority, finance, and military command.', ['political-letter', 'argentina', 'monarchy', 'inca-plan', 'state-formation']),
  passage('pass-tucuman-order-decree-1816', 'history', 'src-argentina-tucuman-order-1816', '1 August 1816 decree, complete', 'The congress declares an end to revolution', 'Congress answers internal division with obedience, severe penalties, and a tightly bounded right of petition.', ['state-record', 'argentina', 'order', 'coercion', 'civil-conflict']),
  passage('pass-plan-iguala-1821', 'history', 'src-mexico-plan-iguala-1821', 'preamble and selected complete bases 1–5, 8–9, 11–14, 16, 20, and 23', 'A military plan joins independence to monarchy and guarantees', 'The settlement combines Catholic establishment, constitutional monarchy, dynastic succession, military protection, property, clerical privilege, and future constituent Cortes.', ['political-plan', 'mexico', 'monarchy', 'military', 'three-guarantees']),
  passage('pass-mexico-independence-act-1821', 'history', 'src-inehrm-mexico-independence-act-1821', '28 September 1821 act, complete substantive declaration', 'Sovereignty declared through the Iguala settlement', 'The Junta declares sovereign nationhood while expressly binding constitutional construction to the Plan of Iguala and Treaty of Córdoba.', ['state-record', 'mexico', 'independence', 'sovereignty', 'imperial-settlement']),
  passage('pass-peru-lima-independence-act-1821', 'history', 'src-peru-bicentennial-independence-act-1821', '15 July 1821 act, complete substantive text', 'A capital assembly certifies a general will', 'Lima officials, clergy, titled elites, and selected residents answer San Martín’s request by speaking for the capital and the general will.', ['municipal-record', 'peru', 'lima', 'independence', 'representation']),
  passage('pass-peru-protector-decree-1821', 'history', 'src-peru-congress-protector-decree-1821', '3 August 1821 decree, selected complete paragraphs and Articles 1 and 7', 'Proclamation followed by war government', 'San Martín states that enemies remain, unites political and military command in the free departments, and defers permanent form until national representatives can meet.', ['state-record', 'peru', 'protectorate', 'war', 'provisional-government']),
  passage('pass-brazil-manifesto-peoples-1822', 'history', 'src-bndigital-brazil-manifesto-peoples-1822', 'Gazeta do Rio supplement 94, 6 August 1822, print pages 247–248, selected complete paragraphs', 'A manifesto makes provinces into a projected union', 'The prince’s manifesto claims sovereignty, demands a Brazilian assembly, and converts provincial plurality into a program of union and independence.', ['political-manifesto', 'brazil', 'provinces', 'constitutional-monarchy', 'union']),
  passage('pass-brazil-council-session-1822', 'history', 'src-brazil-chamber-council-session-1822', 'Council session 13, 2 September 1822, complete surviving extract', 'A council turns news into measures for war', 'Under Leopoldina’s presidency the council answers Lisbon with financial reprisal, security measures, and a campaign plan rather than a theatrical cry.', ['council-record', 'brazil', 'leopoldina', 'war-planning', 'collective-decision']),
  passage('pass-cachoeira-adhesion-letter-1822', 'history', 'src-cachoeira-adhesion-letter-1822', '28 June 1822 letter, quoted substantive paragraphs', 'A provincial adhesion made under fire', 'Cachoeira recognizes Pedro as constitutional regent while reporting Portuguese bombardment, making provincial choice and warfare part of independence.', ['municipal-letter', 'brazil', 'bahia', 'provincial-adhesion', 'war']),
  passage('pass-commons-apprenticeship-debate-1838', 'history', 'src-hansard-apprenticeship-debate-1838', 'HC Deb 29 March 1838, volume 42, selected Strickland and Grey paragraphs', 'Parliament disputes whether deferred freedom is protection or compensation', 'The motion for an August 1838 end confronts material failure, while the government defends apprenticeship as a compact with proprietors.', ['parliamentary-debate', 'british-empire', 'apprenticeship', 'compensation', 'contested-policy']),
  passage('pass-barbados-apprenticeship-termination-1838', 'history', 'src-unb-barbados-apprenticeship-termination-1838', 'CO 28/125, pages 58–59, title and selected clause abstracts', 'A colonial legislature terminates praedial apprenticeship', 'The Barbados record cancels the remaining term while temporarily restricting ejection and retaining limited support obligations.', ['colonial-law', 'barbados', 'apprenticeship', 'emancipation', 'transition'])
];

export const ATRIUM_SOURCES = Object.freeze(sourceCandidates.map(candidate => {
  const audit = ATRIUM_SOURCE_AUDITS[candidate.id];
  if (!audit) return candidate;
  return {
    ...candidate,
    ...audit,
    rights: { ...candidate.rights, ...audit.rights }
  };
}));

const auditedSourceRights = new Map(ATRIUM_SOURCES
  .filter(item => item.status === 'publishable')
  .map(item => [item.id, item.rights.status]));

export const ATRIUM_PASSAGES = Object.freeze(passageCandidates.map(candidate => {
  const audit = ATRIUM_PASSAGE_AUDITS[candidate.id];
  return {
    ...candidate,
    ...(auditedSourceRights.has(candidate.sourceId)
      ? { rightsStatus: auditedSourceRights.get(candidate.sourceId) }
      : {}),
    ...(audit || {})
  };
}));

export const ATRIUM_CATALOG = freezeManifest({
  id: 'atrium-source-and-passage-candidates',
  label: 'Atrium source and passage candidates',
  schemaVersion: ATRIUM_SCHEMA_VERSION,
  corpusVersion: ATRIUM_CORPUS_VERSION,
  status: 'draft',
  sources: ATRIUM_SOURCES,
  passages: ATRIUM_PASSAGES
});

export function findAtriumSource(id) {
  return ATRIUM_SOURCES.find(item => item.id === id) || null;
}

export function findAtriumPassage(id) {
  return ATRIUM_PASSAGES.find(item => item.id === id) || null;
}
